### ISSUE TITLE
Return code for nonlinear solvers

### ISSUE THREAD

**Issue by YingboMa** [SciML/DifferentialEquations.jl#178]
There isn't a return code in the [nonlinear solvers API](http://docs.juliadiffeq.org/latest/features/linear_nonlinear.html#Nonlinear-Solvers:-nlsolve-Specification-1) for now. This is needed, because there is no way no know if the nonlinear solver converges. For instance, the [return code of the BVP solver](https://github.com/JuliaDiffEq/BoundaryValueDiffEq.jl/blob/master/src/solve.jl#L16-L17) depends on the nonlinear solver's return code.

**Comment by ChrisRackauckas** [comment]
Thanks for the issue. I agree this is necessary. Fortunately, it wouldn't be too hard to change. As is proposed in the BVP solvers, I think `(zero,retcode)` is a good API extension. The steps to make this ecosystem-wide change is:

1) Update the default nlsolver setup in OrdinaryDiffEq.jl
2) Update how the nlsolvers are used in OrdinaryDiffEq.jl (i.e. checking retcodes and using the first part of the tuple). (Update the tests as well)
3) Update Sundials.jl's simple `Kinsol` API to return `(zero,retcode)`.
4) Update the docs to specify this new form.

However, the only worrysome thing is that I don't know of a good way to "tell users this changed", i.e. there doesn't seem to be an easy upgrade or deprecation path here. But, this is a very deep part of the API which most users probably aren't making use of, so I hope it's okay to just make this change?

I will handle the ecosystem parts, and you can develop the BVP solvers knowing that will be the eventual API.

**Comment by ChrisRackauckas** [comment]
There is now. `sol.retcode`, which is SciML Base enums, etc. Finally.
