### ISSUE TITLE
Throw an error if we see a non-common interface argument.

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DifferentialEquations.jl#334]
If `init` or `solve` get a kwarg which isn't a common interface argument, they should just throw an error. This can be checked at compile time now that kwargs are specialized iterables which are essentially NamedTuples

**Comment by tkf** [comment]
Why not just "throw if there is an unsupported keyword argument?"  For example, I think initializing ODE solver should throw if you pass options that are meaningful only for PDE solver.

**Comment by tkf** [comment]
Ah, I guess what you mean by common interface argument is the option that are supported/meaningful to all DiffEq solvers?  Then what I said would be equivalent to what you wrote.

**Comment by ChrisRackauckas** [comment]
>I guess what you mean by common interface argument is the option that are supported/meaningful to all DiffEq solvers?

Yup.
