### ISSUE TITLE
Move API docs from DiffEqDocs.jl to docstrings?

### ISSUE THREAD

**Issue by tkf** [SciML/DifferentialEquations.jl#371]
It would be nice if `?solve`, `?ODEFunction` etc. shows their documentation.  Also, making two PRs for XXXDiffEq.jl and DiffEqDocs.jl is rather inefficient.

I tried including some existing docstrings from DiffEqBase.jl here and it works: https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/166

**Comment by ChrisRackauckas** [comment]
I agree that using docstrings would be nice. I hate the giant boxes it puts around every function when you do that.

**Comment by tkf** [comment]
> gigantic box

You mean the gray border around the docstring like this?

![image](https://user-images.githubusercontent.com/29282/47244915-2564d180-d3ac-11e8-94f9-31656dffae98.png)

I guess you can tweak the CSS to remove them. I've never tried though.

**Comment by tkf** [comment]
Do you want something like this?

![image](https://user-images.githubusercontent.com/29282/47246186-5398e000-d3b1-11e8-9523-0221afc08667.png)

**Comment by ChrisRackauckas** [comment]
Ehh if we go with this I think that we might as well use the normal CSS. It looks fine for the portion you've submitted. I'm just thinking that, for example, updating this page to all be docstrings:

http://docs.juliadiffeq.org/latest/solvers/ode_solve.html#Runge-Kutta-Methods-for-Non-Stiff-Equations-1

It'll be huge given the normal CSS. The border really isn't the problem, it's that it doesn't go well into a list.

**Comment by tkf** [comment]
Ah, I see.  I think you can use [`@eval block`](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@eval-block-1) to inject auto-generated `Markdown.MD`.

For example, I used similar trick to generate

https://tkf.github.io/PyBase.jl/latest/#List-of-supported-methods-1

from

* https://raw.githubusercontent.com/tkf/PyBase.jl/master/docs/src/index.md
* https://github.com/tkf/PyBase.jl/blob/bfaa050362204d913c41294d8092a10ffe097b0a/src/supported_methods.jl#L7

But I think you need to extract docstring yourself...  I think it would be nice to have this in Documenter.jl.  Python's documentation generator has this functionality http://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html so I think it makes sense for Julia to have one.

**Comment by tkf** [comment]
Actually, it makes sense to have it in `OrdinaryDiffEq` etc. since it'd be nice to read the list of algorithms in REPL.  You can do something like this


```julia
module FakeODEModule

"""
The canonical forward Euler method. Fixed timestep only.
"""
struct Euler end

"""
The second order midpoint method. Uses embedded Euler method for adaptivity.
"""
struct Midpoint end

function bullet(header, doc)
    md = sprint(show, "text/markdown", doc)
    indented = join(string.(Ref("   "), split(md, "\n")), "\n")
    return """
    * $header
    $indented
    """
end

using Markdown
algorithms = Markdown.parse(join([
    bullet("`Euler`:", @doc Euler),
    bullet("`Midpoint`:", @doc Midpoint),
], "\n"))

end  # module
```

then in REPL:

![image](https://user-images.githubusercontent.com/29282/47247599-965eb600-d3b9-11e8-9ced-4108b8c46212.png)

You can easily inject it via Documenter by

```markdown
    ```@eval
    FakeODEModule.algorithms
    ```
```


(the `bullet` helper function above is rather ad-hoc though...)

**Comment by ChrisRackauckas** [comment]
It would be nice to have it all accessible from the REPL like that.

**Comment by ChrisRackauckas** [comment]
I think that at least for OrdinaryDiffEq.jl, it would be helpful if that list was somehow self-populated from the docstrings. But we do want to have the sections...

**Comment by tkf** [comment]
> self-populated

Like listing non-abstract subtypes of `AbstractODEAlgorithm`?

> we do want to have the sections

I guess we can "abuse" abstract types to map one abstract type to one section.  Though it doesn't sound like a good idea to do this only for documentation.

But we need such information stored somewhere anyway, right? It's just now it's embedded in the markdown file. Having such information as a Julia object sounds better. We can then use it to generate documentation. Something like:

```julia
const method_list = Dict(
    :rk => [
        Euler,
        Midpoint,
        ...
    ],
    :rk_with_lazy_interpolant => [
        BS5,
        Vern6,
        ...
    ],
    ...
)
```

Or maybe something trait-based?  Like `is_runge_kutta`, `has_lazy_interpolant`?  I imagine some of the existing traits already have this kind of information.

**Comment by ChrisRackauckas** [comment]
A proper method list would probably be useful for cleaning up some of our tests.

**Comment by tkf** [comment]
Good.  Explicit listing is also good for controlling the order in the document.

**Comment by StanczakDominik** [comment]
I ran into this recently. There's no reference to DiffEqDocs in the currently empty docstrings, so, as a new user, I just assumed the methods I was using were undocumented.

**Comment by ChrisRackauckas** [comment]
done
