### ISSUE TITLE
ArrayPartition doesn't work with SDE problems

### ISSUE THREAD

**Issue by yha** [SciML/DifferentialEquations.jl#386]
Example:
```
f(dy,y,p,t) = (dy .= y)
g(σ,y,p,t) = (σ .= y)
tspan = (0.0,1.0)
y0 = ArrayPartition([0.0],[0.0])
prob = SDEProblem( f, g, y0, tspan )
s = solve(prob)
```
produces
`DimensionMismatch("destination axes (Base.OneTo(1),) are not compatible with source axes (Base.OneTo(2),)")`

**Comment by ChrisRackauckas** [comment]
This has been working for awhile. Thanks for the report!
