### ISSUE TITLE
Monte Carlo simulations of JumpProblems with VariableRateJump

### ISSUE THREAD

**Issue by pihop** [SciML/DifferentialEquations.jl#417]
I'm experiencing unexpected behaviour when trying to use MonteCarloProblem for solving jump processes with VariableRateJumps. 

For example the following problem.
```
using DifferentialEquations
using Plots

function f(du,u,p,t)
    du[1] = 0 
end

affect!(integrator) = (integrator.u[1] = 1.)

jump = VariableRateJump((u,p,t) -> t, affect!)
prob = ODEProblem(f,  [0.], (0., 10.0))
```

Plotting the following gives expected behaviour with trajectories showing a range of times where the jump from 0. to 1. happens.
```
plt1 = plot()
for i = 1:200
    jump_prob = JumpProblem(prob, Direct(), jump)
    sol = solve(jump_prob, Tsit5())
    plt1 = plot!(sol, , label="")
end
```

Using MonteCarloProblem, as follows, results in a set of trajectories which jump from 0. to 1. at the same time.
```
jump_prob = JumpProblem(prob, Direct(), jump)
monte_prob = MonteCarloProblem(jump_prob)
@time sol_monte = solve(monte_prob, num_monte=200)
plt2 = plot(sol_monte)
```

**Comment by ChrisRackauckas** [comment]
This got fixed but we forgot to close the issue. It has tons of tests now so that it doesn't pop up again. Thanks!
