### ISSUE TITLE
save_onlyend simple argument syntax for solve only returning the end time

### ISSUE THREAD

**Issue by jessebett** [SciML/DifferentialEquations.jl#448]
Finding myself needing to only solve for the final state. It would be nice if there was an argument that makes this clear.

i.e. have it be a synonym to `save_start=false,save_everystep=false`

**Comment by ChrisRackauckas** [comment]
I'm going to veto this: we have enough saving options already, and `save_start=false,save_everystep=false` is "good enough". Adding redundancy will get confusing. But thanks for the idea.
