### ISSUE TITLE
Re-branding for multiple language compatibility

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DifferentialEquations.jl#519]
DifferentialEquations.jl has become a cross-language platform and Julia is becoming a language of libraries which other programming languages are building packages from, and so it is time to think about what the branding now needs to be. I think DifferentialEquations.jl as a name for the Julia package is solidified, but I think it may be a good idea to change JuliaDiffEq to something more appropriate. Anyone have any ideas? DiffEq on its own may be too simple, and the name is taken on Github. The one I've liked best is TotalDiffEq.

**Comment by taqtiqa-mark** [comment]
LibDiffEqn or DiffEqnLib ?

**Comment by BeastyBlacksmith** [comment]
`DiffEqUniverse`, `DiffEqUnite`,  `TheDiffEq`

**Comment by msaroufim** [comment]
+1 DiffEqUniverse

**Comment by ChrisRackauckas** [comment]
Oh this should be closed. We went with SciML because by the time the rename happened, the organization grew to include a few other things
