### ISSUE TITLE
"using DifferentialEquations" is very slow

### ISSUE THREAD

**Issue by ma-sadeghi** [SciML/DifferentialEquations.jl#555]
`using DifferentialEquations` roughly takes ~15 seconds on my 2013 Macbook. Is that normal?

**Comment by freemin7** [comment]
I see a similar wait time with this configuration.
```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
Generic packages (like Plot something or solve some DGL tend to take long to compile/load)

**Comment by ChrisRackauckas** [comment]
Indeed, the full DiffEq pulls in a lot and can have a startup time. This is something that is being worked on in the Julia Base repo. For now, you can use sub-packages, like OrdinaryDiffEq, if you want faster startups and just want one thing like ODEs.

**Comment by ma-sadeghi** [comment]
Hi @ChrisRackauckas, any progress on this front by any chance?

**Comment by ChrisRackauckas** [comment]
See https://github.com/SciML/DifferentialEquations.jl/issues/786 and https://sciml.ai/news/2021/08/31/czi/ . So yeah, tons going on there. We'll track it in those issues.
