### ISSUE TITLE
Example of using DifferentialEquations.jl for SIR model on a graph

### ISSUE THREAD

**Issue by Omer80** [SciML/DifferentialEquations.jl#583]
Hello, I am now using a Python code for simulating stochastic epidemiological models on graphs, where the nodes are individual people (using networkx). As I understand Julia may be much faster for such computations. Is there anywhere an example to be found on how to build such a model using DifferentialEquations.jl ? (I am quite a beginner in Julia)

**Comment by ChrisRackauckas** [comment]
@FHell was working on https://github.com/FHell/NetworkDynamics.jl

**Comment by FHell** [comment]
Thanks for the @ Chris. Hi @Omer80, if you write to me at hellmann@pik-potsdam.de I am happy to put you in touch with somebody on our end that can help you implement this in NetworkDynamics.

**Comment by ChrisRackauckas** [comment]
Closing since there's not much for me to act on here, but good luck on your modeling journey.
