### ISSUE TITLE
Using remake for EnsembleProblem

### ISSUE THREAD

**Issue by rveltz** [SciML/DifferentialEquations.jl#586]
Hi,

I am a bit confused by the following. I thought that `remake` was the factory standard for say modifying an `ODEProblem`, like `u0` for example. Now, the [docs](https://docs.sciml.ai/dev/features/ensemble/#Example-1:-Solving-an-ODE-With-Different-Initial-Conditions-1) at DE for Ensemble simulation are showing piece of code where `u0` is modified directly in the struct.

1. Are the docs up to date? 
2. What is advised to do?

Thank you for your help,

Best regards

**Comment by ChrisRackauckas** [comment]
I updated the docs to use `remake` everywhere since that's what's recommended and a lot more flexible than what was previously in the docs. https://github.com/SciML/DiffEqDocs.jl/commit/7990e8e1610af56ada7b27b68671879643a22e5e

**Comment by rveltz** [comment]
That's what I use [here](https://github.com/rveltz/PseudoArcLengthContinuation.jl/blob/master/src/periodicorbit/Flow.jl#L17). 

Thank you
