### ISSUE TITLE
DABDF2 fails with discrete callbacks

### ISSUE THREAD

**Issue by rodrigomha** [SciML/DifferentialEquations.jl#589]
The following example fails with DABDF2:
```
f = function (out,du,u,p,t)
  out[1] = - p[1]*u[1]              + p[3]*u[2]*u[3] - du[1]
  out[2] = + p[1]*u[1] - p[2]*u[2]^2 - p[3]*u[2]*u[3] - du[2]
  out[3] = u[1] + u[2] + u[3] - p[4]
end
u₀ = [1.0, 0, 0]
du₀ = [0.0, 0.0, 0.0]
p = [0.04, 3.0e7, 1.0e4, 1.0]
tspan = (0.0,100.0)
differential_vars = [true,true,false]
prob = DAEProblem(f,du₀,u₀,tspan,p,differential_vars=differential_vars)
condition(u,t,integrator) = t in [50.0]
affect!(integrator) = integrator.p[4] += 1.0
cb = DiscreteCallback(condition,affect!)
sol = solve(prob, DABDF2(), callback=cb, tstops=[50.0])
```
That gives the following error:
```
MethodError: no method matching (::var"#35#36")(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64)
Closest candidates are:
  #35(::Any, ::Any, ::Any, ::Any, !Matched::Any) at In[59]:2
```

Note that this does not fail with DImplicitEuler. I have not tried yet the case with Continuous callbacks.

**Comment by ChrisRackauckas** [comment]
This is also pointing out to me that we need to do the FSAL setup as well so that we get a higher order interpolation here. @kanav99

**Comment by kanav99** [comment]
Yes, lets make fsal work in DAEs. I started a PR https://github.com/SciML/OrdinaryDiffEq.jl/pull/1105 
@rodrigomha You can checkout OrdinaryDiffEq to branch `daefixes` to see if it works for you

**Comment by rodrigomha** [comment]
> Yes, lets make fsal work in DAEs. I started a PR [SciML/OrdinaryDiffEq.jl#1105](https://github.com/SciML/OrdinaryDiffEq.jl/pull/1105)
> @rodrigomha You can checkout OrdinaryDiffEq to branch `daefixes` to see if it works for you

Hi, sorry to came back this late. Sadly, the fixes on that branch are still not working. The error is different though. It complains that requires more `maxiters`, but even if in the solve I use `maxiters=Inf`, the algorithm never ends.

**Comment by ChrisRackauckas** [comment]
Yes, we need to do a bit more on that branch. I discussed it with @kanav99 already, but it'll take a little bit. I won't be able to get to it for at least a week, and I don't know if @kanav99 planned to pick it up earlier

**Comment by rodrigomha** [comment]
Sure, there is no problem.
Thanks!

**Comment by kanav99** [comment]
Yeah sorry I got a bit caught up in something, I will try to complete this one as soon as I could.

**Comment by jd-lara** [comment]
bump @kanav99 and @ChrisRackauckas about this issue. We are planning to test pure Julia solvers but not sure if this got resolved.

**Comment by ChrisRackauckas** [comment]
DABDF2 won't perform as well as Sundials, so for now I would recommend targeting the common interface and using IDA, and we can then start using your code as a benchmark to improve these methods. We'll want a full adaptive order BDF before taking on the biggest problems.

**Comment by ChrisRackauckas** [comment]
Though @kanav99 if you have time, all that needs to be done here is to initialize after callback changes IIRC.

**Comment by ChrisRackauckas** [comment]
The workaround would be to call `reinit!(integrator)` after your `affect!` is applied.

**Comment by TobiasFranzBRB** [comment]
It is still not possible to use DiscreteCallback with the DABDF2 solver. What's the best alternative to apply callbacks on DAE problems with the DABDF2 solver? How should I use reinit! in this context? @ChrisRackauckas

**Comment by TobiasFranzBRB** [comment]
many Thanks @ChrisRackauckas . Keep up the great work. Really enjoy working with DiffEq library especially for solving DAE systems.
