### ISSUE TITLE
Event repeated at the same time using ContinuousCallback and adaptive = false

### ISSUE THREAD

**Issue by BeastyBlacksmith** [SciML/DifferentialEquations.jl#590]
The following used to work on julia 1.1 with OrdinaryDiffEq v5.16.0, but fails on 1.4 with OrdinaryDiffEq v5.33.0:
```julia
using Pkg
Pkg.add("https://gitlab.gwdg.de/PhD/VesiclesForms.jl/")
```
```julia
vesicle = VesicleForms.critSphere
        sol = VesicleForms.integrate_shapeEquations( vesicle, (0.0,1.2), callback = VesicleForms.pi_callback, adaptive = false, alg = Vern7() )
```
Removing either the callback or the adaptiveness, does not error, but also does not produce the desired result.

**Comment by ChrisRackauckas** [comment]
Probably related to some of the @kanav99 callback changes. Diagnosing this is very subtle though, so wait a few days and we'll figure out what's going on.
