### ISSUE TITLE
Discrete stochastic simulations method error

### ISSUE THREAD

**Issue by Skumin** [SciML/DifferentialEquations.jl#594]
I'm trying to follow the steps on [this](https://docs.sciml.ai/release-1.8/tutorials/discrete_stochastic_example.html#Discrete-Stochastic-(Gillespie)-Equations-1) page in the docs but I cannot make it work. First, the `Reaction` constructor does not seem to exit in either `DifferentialEquations` or `DiffEqBiological`. Seeing this, I've proceeded to the section Defining the Jumps Directly but the `Discrete()` function is undefined too. If I remove it completely or replace it with `FunctionMap()`, I get a method error in the `solve` call: `MethodError: no method matching (::var"#9#10")(::Array{Int64,1}, ::DiffEqBase.NullParameters, ::Float64)`. The code I'm trying to run is as follows:
```julia
using DifferentialEquations, DiffEqBase, DiffEqBiological

rate = (t,u) -> (0.1/1000.0)*u[1]*u[2]
affect! = function (integrator)
  integrator.u[1] -= 1
  integrator.u[2] += 1
end
jump = ConstantRateJump(rate,affect!)

rate = (t,u) -> 0.01u[2]
affect! = function (integrator)
  integrator.u[2] -= 1
  integrator.u[3] += 1
end
jump2 = ConstantRateJump(rate,affect!)

prob = DiscreteProblem([999,1,0],(0.0,250.0))
# jump_prob = JumpProblem(prob,jump,jump2) # Does not work, need an aggregator
jump_prob = JumpProblem(prob, Direct(), jump, jump2)
# sol = solve(jump_prob, Discrete(apply_map=false)) # Does not work, Discrete is undefined
sol = solve(jump_prob, FunctionMap()) # Method error here
```

**Comment by ChrisRackauckas** [comment]
Some how you found the DifferentialEquations.jl v1.8 docs, which are about 4 years old. DifferentialEquations.jl v6.12 is the current version, and this is documented in the current stable docs: https://docs.sciml.ai/release-1.8/tutorials/discrete_stochastic_example.html#Discrete-Stochastic-(Gillespie)-Equations-1
