### ISSUE TITLE
Flag for saving outputs of inplace functions

### ISSUE THREAD

**Issue by jonniedie** [SciML/DifferentialEquations.jl#609]
It would be helpful to have a `save_output` solver keyword argument to save the output of inplace functions. A linear state space model, for example:

```julia
using DifferentialEquations

function ss_fun!(dx, x, p, t)
    A, B, C, D, input_fun = p
    u = input_fun(t)

    dx .= A*x + B*u
    return C*x + D*u
end

A = [0 1; -1 -4.5]
B = [0; 1.0]
C = [0.5 0.5]
D = [1.0]
u = t -> sin(t)
p = (A, B, C, D, u)

x₀ = zeros(size(A,1))

prob = ODEProblem(ss_fun!, x₀, (0.0, 10.0), p)
sol = solve(prob, save_output=true)
```

Really this just a nice-to-have for not having to create a `SavingCallback`, so not necessarily a priority.

**Comment by ChrisRackauckas** [comment]
This is a cool idea, but I don't see it happening any time soon because it will require a ton of work, i.e. a change to every single method we've ever written.

**Comment by ChrisRackauckas** [comment]
Also, this doesn't play nicely with interpolations, so it's not actually saving time compared to just saving the differential variables and recomputing these values. So it would be a convenience, but not necessarily an acceleration in most cases.

**Comment by jonniedie** [comment]
That makes sense. No use spending that much effort on something that can be accomplished externally with a simple wrapper around ODEProblem (for the specific example of a linear state-space system, the `Simulator` type from ControlSystems.jl does exactly this). I'm going to go ahead and close this one out. Thanks!
