### ISSUE TITLE
Untested edge case when stepping from the end of a known tspan

### ISSUE THREAD

**Issue by Libbum** [SciML/DifferentialEquations.jl#616]
Full details of this conversation can be found on [this discourse thread](https://discourse.julialang.org/t/handling-unstable-true-solution-issues-with-the-integrator-interface/41208?u=libbum). 

Essentially, when a user uses the integrator interface and steps to the end of a problem's tspan, a `dt <= dtmin. Aborting.` warning will be thrown if a second step is attempted.

A quick example:
```julia
tspan = (0.0, 365.0)
prob = ODEProblem(system, u0, tspan)
integrator = init(prob, Tsit5())
step!(integrator, 365.0, true)
#integrator.t = 365.0
step!(integrator, 365.0, true)
#Warning: dt <= dtmin. Aborting.
```

Possible reason/solution:
> `solve!` goes to `tspan[end]`, and then `step!` could continue from there. Or `step!` could do all of it, but I think if you `step!` to the end then continue, it might hit a weird floating point bug since it’ll be `1e-16` away from the true end or something like that.  --Chris

**Comment by ChrisRackauckas** [comment]
@utkarsh530 would you mind looking into this?

**Comment by utkarsh530** [comment]
Yeah Sure! I will look into it.
