### ISSUE TITLE
 MethodError: no method matching similar(::Float64) when using a vector of dimension 1

### ISSUE THREAD

**Issue by bhache** [SciML/DifferentialEquations.jl#619]
Hello,
I am new to Julia and trying my hands at the differential equations package.

I followed the parameterized Lorenz example and tried to modify it to the system of equations I want to work with. Instead of starting with a full system I wanted to see the behavior with only one equation which is not coupled with any other equations in the system and this is when I run into the error and not sure what to make of it. Any help would be much appreciated. thank you.

```Julia
#%% Loading packages
using DifferentialEquations    # Differential equations package
using Plots                    # Plot package

#%% Differential Equation for Resting Potential
function RestingPotential!(dV, V, p, t)
    Gu, Et, G_K, E_Kp, C_ab = p;
    dV = -(Gu*(V - Et) + G_K*(V - E_Kp))/C_ab;
end

#%% Receptor Potential Generation
# Apex
G_max = 8.8771;         # MET maximum conductance (nS)
s0 = 85;                # Displacement sensitivity (nm)
u0 = 7;                 # Displacement offset (nm)
s1 = 5;                 # Displacement sensitivity (nm)
u1 = 7;                 # Displacement offset (nm)
Et = 90;

# Base
G_K = 18;               # Potassium channel conductance (nS)
E_K = -75;              # Potassium ion reversal potential (mV), Nam FEM model

# common
C_ab = 6;               # Total membrane capacitance (pF)
E_Kcor = 0.04;          #
E_Kp = E_K + E_Kcor * Et;# Corrected Potassium ion reversal potential (mV)

# Compute apical conductance
Gu = G_max/(1+exp(u0/s0)*(1+exp(u1/s1)));

V0 = (Gu*Et + G_K*E_Kp)/(Gu + G_K);
p = [Gu Et G_K E_Kp C_ab];
tspan = (0.0, 100.0);

prob = ODEProblem(RestingPotential!, V0, tspan, p)
sol = solve(prob);

gr()
plot(sol,vars=(1))
```

MethodError: no method matching similar(::Float64)
Closest candidates are:
  similar(!Matched::JuliaInterpreter.Compiled, !Matched::Any) at /home/user/.julia/packages/JuliaInterpreter/jYH1M/src/types.jl:7
  similar(!Matched::Sundials.NVector) at /home/user/.julia/packages/Sundials/LzbrB/src/nvector_wrapper.jl:71
  similar(!Matched::Array{T,1}) where T at array.jl:356
  ...
in  at OrdinaryDiffEq/NsugH/src/solve.jl:66
in #__init#361 at OrdinaryDiffEq/NsugH/src/solve.jl:271
in alg_cache at OrdinaryDiffEq/NsugH/src/caches/basic_caches.jl:21
in map at base/tuple.jl:158
in  at OrdinaryDiffEq/NsugH/src/caches/basic_caches.jl:22
in alg_cache at OrdinaryDiffEq/NsugH/src/caches/low_order_rk_caches.jl:356

**Comment by ChrisRackauckas** [comment]
You cannot do scalar ODEs with in-place mutating forms.

```
function RestingPotential!(V, p, t)
    Gu, Et, G_K, E_Kp, C_ab = p;
    -(Gu*(V - Et) + G_K*(V - E_Kp))/C_ab;
end
```

will work, or if `V0 = [(Gu*Et + G_K*E_Kp)/(Gu + G_K)]` then

```julia
function RestingPotential!(dV, V, p, t)
    Gu, Et, G_K, E_Kp, C_ab = p;
    dV[1] = -(Gu*(V[1] - Et) + G_K*(V[1] - E_Kp))/C_ab;
end
```

will work. The former is more optimized for these small scalar scenarios, while the latter is more optimized for real array-based solutions.

**Comment by bhache** [comment]
Thank you for a prompt reply, sorry for the trivial nature of the question and I will try that. Also, how would one deal with the case of a time varying parameter which is predefined on a time grid that might be different from the internal time grid of the solver?

**Comment by ChrisRackauckas** [comment]
Either use `tstops` and `adaptive=false` to force the solver to hit the time points (not the best idea, but it would work), or a better idea is to interpolate the data using something like https://github.com/PumasAI/DataInterpolations.jl to make it a continuous function that can be used in the ODE.

**Comment by ChrisRackauckas** [comment]
Sounds like this is all good, so I'll close. Have fun exploring Julia. You may want to join the Discourse: https://discourse.julialang.org/ or the Slack: slackinvite.julialang.org.

**Comment by bhache** [comment]
It worked! Thank you.
