### ISSUE TITLE
Sundials FunJac - MethodError

### ISSUE THREAD

**Issue by ryakoub** [SciML/DifferentialEquations.jl#631]
Hi,

I am getting this error:

MethodError: no method matching Sundials.FunJac(::Sundials.var"#82#86"{DAEProblem{Array{Int64,1},Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,DAEFunction{true,typeof(PendulumI3),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Array{Bool,1}},Tuple{Int64},Tuple{Int64}}, ::Nothing, ::Nothing, ::DiffEqBase.NullParameters, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Array{Int64,1}, ::Array{Float64,1}, ::Array{Float64,1})

I am following the footsteps as described in the DAE example.  Here is my model:
function PendulumI3(f, du, u, p, t)
  m,L,g = p
  x,y,vx,vy,λ = u
  f[1]=vx-du[1]
  f[2]=vy-du[2]
  f[3]=m*du[3] + 2x*λ
  f[4]=m*du[4] +2y*λ + m*g
  f[5]=x*x+y*y-L*L
end
differential_vars = [true,true,true,true,false]
u0 = [1,0,0,0,0]
du0 = [0,0,0,-9.8,0]
p = (1.0, 1.0, 9.8)
tspan = (0.0, 5.0)
model = DAEProblem(PendulumI3,du0,u0,tspan, p,differential_vars=differential_vars)
pend_sol1 = solve(model,IDA())

two questions: why it is searching for explicit FunJac?
I want to provide my own Jacobian, what is the syntax and the order of partial? is it du then u? should du include the non-derivative vars?

**Comment by ChrisRackauckas** [comment]
The issue was that `u0 = [1,0,0,0,0]` was integers. `u0 = [1.0,0.0,0.0,0.0,0.0]` fixes that issue ,and SciML/DiffEqBase.jl#544 will make that automatic. Thanks for the report!

BTW, you will still have issues on this problem because it is an index-2 DAE. See Problem 3 from https://tutorials.sciml.ai/html/exercises/02-workshop_solutions.html for help on this.
