### ISSUE TITLE
DPRKN6 doesn't appear to use its free 6th order interpolant

### ISSUE THREAD

**Issue by npbarnes** [SciML/DifferentialEquations.jl#633]
The documentation says DPRKN6 has a free 6th order interpolant, but solutions don't appear to use it.
Example:
```julia
julia> f(v,x,p,t) = -1.1x;
julia> prob = SecondOrderODEProblem(f, 0.0, 1.0, (0.0, 10.0));
julia> sol = solve(prob, DPRKN6())
retcode: Success
Interpolation: 3rd order Hermite
.
.
.
```

**Comment by ChrisRackauckas** [comment]
It was just printing the wrong thing. It still used the 6th order interpolation though. The print is fixed in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1207
