### ISSUE TITLE
Need help in Second order Differential equation

### ISSUE THREAD

**Issue by SaravananThanigachalm** [SciML/DifferentialEquations.jl#634]
I'm new to julia programming I managed to solve some 1st order ODE, but when I thought to move to the second order I don't know how to use the solver to implement to the required equation.
I want to solve this equation
y" + y = 0
with initial conditions
y(0) = 3
y'(0) = -0.5

Please someone help me

**Comment by ChrisRackauckas** [comment]
Solved in https://stackoverflow.com/questions/62852228/second-order-differential-equation-in-julia

**Comment by ChrisRackauckas** [comment]
yay points
