### ISSUE TITLE
Question about setting a "shutdown" condition

### ISSUE THREAD

**Issue by zhiyuanzhai** [SciML/DifferentialEquations.jl#638]
Suppose I have an ODE `du/dt = 2u, u(0)=1`, and I would like to solve it starting with `t=0` and stopping as soon as `u=2`. 
Is there a way I can do that?

**Comment by ChrisRackauckas** [comment]
Yes, see https://docs.sciml.ai/latest/features/callback_functions/#Example-2:-Terminating-an-Integration-1 . Hope that helps!

**Comment by ChrisRackauckas** [comment]
Closing because that should be the solution. Let me know if there's more.

**Comment by zhiyuanzhai** [comment]
> Yes, see https://docs.sciml.ai/latest/features/callback_functions/#Example-2:-Terminating-an-Integration-1 . Hope that helps!

That works perfectly. Thanks!
