### ISSUE TITLE
[feature request] DEStats results for the adjoint process when calculating gradients

### ISSUE THREAD

**Issue by samuela** [SciML/DifferentialEquations.jl#639]
It would be great if there was a way to get `DEStats` information for the "backwards" pass when calculating gradients! I know that it's possible to do so with lower-level parts of DiffEqSensitivities, but having a more direct interface would be very convenient.

**Comment by ChrisRackauckas** [comment]
Agreed. The hard part here is API. If an AD library just returns gradients, then 🤷 . But that's what Zygote, Tracker, ReverseDiff, etc. all do (and even in other languages I think?), so I'm not sure of a way to add extra returns to that.

**Comment by samuela** [comment]
Yeah, that makes sense. Perhaps this is better left accessible through DiffEqSensitivity as it is currently done.
