### ISSUE TITLE
Could not load symbol `jl_function_ptr`

### ISSUE THREAD

**Issue by MartinOtter** [SciML/DifferentialEquations.jl#644]
I switched from Julia 1.3.1 to 1.5.0 and made "update". Afterwards, ModiaMath does no longer simulate with IDA of Sundials.jl. It seems there is either a change in Julia or in Sundials.jl that breaks some code. The error message is:

```
ERROR: LoadError: could not load symbol "jl_function_ptr":
The specified procedure could not be found. 
```

The issue is at this code fragment:
```
@noinline function old_cfunction(f, r, a)
    ccall(:jl_function_ptr, Ptr{Cvoid}, (Any, Any, Any), f, r, a)
end
```

Maybe you eventually can give a hint what I can do

**Comment by ChrisRackauckas** [comment]
We removed old_cfunction from Sundials awhile ago: https://github.com/SciML/Sundials.jl/pull/219 . I don't think old_cfunction will work on Julia v1.5: it was kind of a hack to get the v1.0 upgrade working but was quickly removed. The new style just does an internal anonymous function and then dispatches on that to build the ccall (trick courtesy of Jameson). For reference, this is the trick we use there instead now: https://github.com/SciML/Sundials.jl/blob/master/src/common_interface/solve.jl#L228-L240 .

Something tells me you're on an old version of Sundials. We updated the Sundials binaries to be the latest version, so you may want to try grabbing Sundials v4.2.5. According to our tests everything from before should work, but let us know if it doesn't.
