### ISSUE TITLE
Need an adjoint for constructor Pair

### ISSUE THREAD

**Issue by Yansf677** [SciML/DifferentialEquations.jl#649]
I use diagm in my function, the following error will raise when I try to calculate the gradient of the function. How can I add the adjoint method for the constructor Pair? Many thanks!
`ERROR: Need an adjoint for constructor Pair{Int64,Array{Float64,1}}`

**Comment by ChrisRackauckas** [comment]
@DhairyaLGandhi this one should be easy, but what do you think is the better way to solve it, adjoint of `diagm` or adjoint of `Pair`?

**Comment by Yansf677** [comment]
> @DhairyaLGandhi this one should be easy, but what do you think is the better way to solve it, adjoint of `diagm` or adjoint of `Pair`?

Then may I ask how to do that?

**Comment by DhairyaLGandhi** [comment]
Adding an adjoint for `diagm` would be better here since a lot of the `Pair` functionality is already handled from #452

Something like 
```julia
@adjoint diagm(x) = diagm(x), \Del -> (diag(\Del),)
```

**Comment by Yansf677** [comment]
> Adding an adjoint for `diagm` would be better here since a lot of the `Pair` functionality is already handled from [FluxML/Zygote.jl#452](https://github.com/FluxML/Zygote.jl/pull/452)
> 
> Something like
> 
> ```julia
> @adjoint diagm(x) = diagm(x), d-> (diag(d),)
> ```

The same error still raises.

**Comment by ChrisRackauckas** [comment]
Did you check out https://github.com/FluxML/Zygote.jl/pull/762 ? I assume @DhairyaLGandhi added a few more things to make the full case work out.

**Comment by Yansf677** [comment]
Nice works!
