### ISSUE TITLE
has_continuous_callback() missing for VectorContinuousCallback

### ISSUE THREAD

**Issue by mchitre** [SciML/DifferentialEquations.jl#662]
When trying to forward diff through an ODE with a `VectorContinuousCallback`, I’m getting:
```
ERROR: MethodError: no method matching has_continuous_callback(::DiffEqBase.VectorContinuousCallback{...})
```

Tracing through a little more, I find that `has_continuous_callback()` is called if `ForwardDiff` is loaded, but they are only defined for:

```
has_continuous_callback(cb::DiscreteCallback) = false
has_continuous_callback(cb::ContinuousCallback) = true
has_continuous_callback(cb::CallbackSet) = !isempty(cb.continuous_callbacks)
has_continuous_callback(cb::Nothing) = false
```
and not for `VectorContinuousCallback`.

Further, if I manually define:
```
DiffEqBase.has_continuous_callback(::DifferentialEquations.VectorContinuousCallback) = true
```
it seems to work OK.

Should it be defined for `VectorContinuousCallback` in the original code base?

My installed versions:
```
  [0c46a032] DifferentialEquations v6.15.0
  [f6369f11] ForwardDiff v0.10.12
```

**Comment by ChrisRackauckas** [comment]
It looks like this is just a missing method. Could you open a PR with this?

**Comment by mchitre** [comment]
Yes, happy to.
