### ISSUE TITLE
Huge pre-compilation time

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/DifferentialEquations.jl#664]
Hi,
I am new to Julia and Sci-ML environment. I would like to know if it's possible to reduce this precompilation time? Are there pre-compiled binaries of Sci-ML packages available as there are many such packages?

``
julia> @time using DifferentialEquations
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
448.939752 seconds (72.07 M allocations: 3.949 GiB, 0.40% gc time)

julia> @time using DifferentialEquations
  0.051637 seconds (42.54 k allocations: 2.081 MiB, 30.13% gc time)

julia>

**Comment by ChrisRackauckas** [comment]
Precompilation only occurs when you install or update packages, so while it is long hopefully it's not something you run into very often. That said, whether precompiled binaries could be shipped is an interesting question. Since they do not have machine code, it sounds almost possible. Given that Julia v1.6 (unreleased) greatly reduces the compilation time for this package, we probably need to see if there's anything we can start to do about precompile times.

**Comment by yewalenikhil65** [comment]
That would be great, especially because the packages like Flux, DiffEqFlux, and NueralPDE require artifacts like CUNN+CUDA . It takes an extraordinary time. Also, I would like to know if the following warning is relevant ?

julia> @time using Flux
┌ Warning: `haskey(::TargetIterator, name::String)` is deprecated, use `Target(; name = name) !== nothing` instead.
│   caller = llvm_compat(::VersionNumber) at compatibility.jl:176
└ @ CUDAnative C:\Users\Nikhil\.julia\packages\CUDAnative\C91oY\src\compatibility.jl:176
1952.715579 seconds (67.52 M allocations: 3.571 GiB, 0.14% gc time)

julia> @time using Flux
  0.162280 seconds (131.48 k allocations: 6.539 MiB)

**Comment by ChrisRackauckas** [comment]
The warning is harmless.

**Comment by ChrisRackauckas** [comment]
Apparently precompile times are quicker on Julia v1.6:

https://github.com/JuliaPlots/Plots.jl/issues/2838#issuecomment-685554698

It would be good to get someone to download the nightly and see what the current stats are for DifferentialEquations.jl

**Comment by yewalenikhil65** [comment]
Hello Sir,
I am still struggling with the installation of packages. I have installed CUDA,CUNN-CUDA, and CUTENSOR packages, which seem to be pre-requisites for NeuralPDE. But still finding the issues with v1.4.2


julia> using DiffEqFlux

julia> using NeuralPDE
[ Info: Precompiling NeuralPDE [315f7962-48a3-4962-8226-d0f33b1235f0]
┌ Error: Could not load CUTENSOR; please file an issue (if on Windows, be sure to install the VS C++ redistributable first)
│   exception =
│    could not load library "C:\Users\Nikhil\.julia\artifacts\804435c7dbe9d002d6caa0a8b3596d11a6faa778\bin\cutensor.dll"│    The specified module could not be found.
│    Stacktrace:
│     [1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109
│     [2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
│     [3] use_artifact_cutensor(::VersionNumber) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:318
│     [4] use_artifact_cuda() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:179
│     [5] __init_dependencies__() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:355
│     [6] __runtime_init__() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:110
│     [7] (::CUDA.var"#609#610"{Bool})() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:32
│     [8] lock(::CUDA.var"#609#610"{Bool}, ::ReentrantLock) at .\lock.jl:161
│     [9] _functional(::Bool) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:26
│     [10] functional(::Bool) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:19
│     [11] functional at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:18 [inlined]
│     [12] __init__() at C:\Users\Nikhil\.julia\packages\Flux\05b38\src\Flux.jl:53
│     [13] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
│     [14] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:781
│     [15] _require(::Base.PkgId) at .\loading.jl:1006
│     [16] require(::Base.PkgId) at .\loading.jl:927
│     [17] require(::Module, ::Symbol) at .\loading.jl:922
│     [18] include(::Module, ::String) at .\Base.jl:377
│     [19] top-level scope at none:2
│     [20] eval at .\boot.jl:331 [inlined]
│     [21] eval(::Expr) at .\client.jl:449
│     [22] top-level scope at .\none:3
│     [23] eval(::Module, ::Any) at .\boot.jl:331
│     [24] exec_options(::Base.JLOptions) at .\client.jl:264
│     [25] _start() at .\client.jl:484
└ @ CUDA C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:320
┌ Error: Could not load CUTENSOR; please file an issue (if on Windows, be sure to install the VS C++ redistributable first)
│   exception =
│    could not load library "C:\Users\Nikhil\.julia\artifacts\804435c7dbe9d002d6caa0a8b3596d11a6faa778\bin\cutensor.dll"│    The specified module could not be found.
│    Stacktrace:
│     [1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109
│     [2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
│     [3] use_artifact_cutensor(::VersionNumber) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:318
│     [4] use_artifact_cuda() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:179
│     [5] __init_dependencies__() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:355
│     [6] __runtime_init__() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:110
│     [7] (::CUDA.var"#609#610"{Bool})() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:32
│     [8] lock(::CUDA.var"#609#610"{Bool}, ::ReentrantLock) at .\lock.jl:161
│     [9] _functional(::Bool) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:26
│     [10] functional(::Bool) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:19
│     [11] functional at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:18 [inlined]
│     [12] __init__() at C:\Users\Nikhil\.julia\packages\Flux\05b38\src\Flux.jl:53
│     [13] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
│     [14] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:781
│     [15] _require(::Base.PkgId) at .\loading.jl:1006
│     [16] require(::Base.PkgId) at .\loading.jl:927
│     [17] require(::Module, ::Symbol) at .\loading.jl:922
│     [18] include(::Module, ::String) at .\Base.jl:377
│     [19] top-level scope at none:2
│     [20] eval at .\boot.jl:331 [inlined]
│     [21] eval(::Expr) at .\client.jl:449
│     [22] top-level scope at .\none:3
│     [23] eval(::Module, ::Any) at .\boot.jl:331
│     [24] exec_options(::Base.JLOptions) at .\client.jl:264
│     [25] _start() at .\client.jl:484
└ @ CUDA C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:320

**Comment by ChrisRackauckas** [comment]
This is unrelated, and anyways, the precompile time is not really actionable here, so I'm going to close this issue. You might want to follow up in the Julia Slack (https://slackinvite.julialang.org/, in the #diffeq-bridged and #sciml channels) or the Discourse (https://discourse.julialang.org/). This is a CUDA installation issue so it's probably best on these places so the GPU devs can see it
