### ISSUE TITLE
[question] Interpolating adjoint for DDEs

### ISSUE THREAD

**Issue by andrschl** [SciML/DifferentialEquations.jl#672]
Hi everyone,

I am trying to implement the interpolating adjoint method for DDEs. It does not seem to be a too difficult change from the ODE version to replace the adjoint ODE with its DDE counterpart and ODE by DDE solvers. However, I am having troubles to locate the pieces of code in the library where these things are implemented.

Can anyone help me out here and give me some hints where to best implement these changes?

Thanks in advance for any help!

Cheers,
Andreas

**Comment by ChrisRackauckas** [comment]
Yeah there's some discussion in https://github.com/SciML/DiffEqSensitivity.jl/issues/281 . Join #diffeq-bridged on the Julia Slack (slackinvite.julialang.org) and we can discuss there. @devmotion might be interested in this too. I think the hard part is resolving the discontinuities though: that's definitely a step (pun intended)!

**Comment by andrschl** [comment]
@ChrisRackauckas thanks a lot for the quick answer and sorry for overlooking this discussion. Yes, I agree this seems to be the main difficulty. I joined the Slack and would be more than happy to discuss it.

**Comment by ChrisRackauckas** [comment]
No worries, it's a huge ecosystem so it can be hard to find the right thing at first. Take care and hope to have you around!
