### ISSUE TITLE
Centralizing the development of .github actions, workflows, and metadata

### ISSUE THREAD

**Issue by lisamartin72** [SciML/DifferentialEquations.jl#673]
Hi SciML project,

I am attaching the URL and the code for your donation button. Most of our sponsored projects have a NF donation button on their websites. Please reach out to me with any questions or concerns at finance@numfocus.org. Have a great weekend and welcome to NumFOCUS!

Best, 

Lisa Martin

https://numfocus.salsalabs.org/donate-to-sciml

```
<a href="https://numfocus.salsalabs.org/donate-to-sciml" target="_blank" style="background:#FFA500;padding:10px;margin:10px 0px;text-align:center;text-decoration:none;font-size:12pt;color:#222222;font-family:Arial, Helvetica, sans-serif;display:inline-block;">Donate Now!</a>
```

**Comment by ChrisRackauckas** [comment]
Hi! Thanks, we'll get this setup. I think what we want to do is move to using an organization-wide actions setup, like https://github.com/arviz-devs/.github . I setup a repo at: https://github.com/SciML/.github We'll need to get that setup with:

- CompatHelper
- Tagbot
- Documentation bot
- Funding.yml
- General repo code of conduct

Pinging @christopher-dG @kanav99 @ScottPJones who usually help with kind of thing.

**Comment by christopher-dG** [comment]
I'll get to this by Monday at the latest.

**Comment by ChrisRackauckas** [comment]
I got the donation link working, so I'll rename this to be about centralizing our .github management. @lisamartin72 thanks!

**Comment by ChrisRackauckas** [comment]
This is good, we can continue in the repo!
