### ISSUE TITLE
ContinuousCallback not firing

### ISSUE THREAD

**Issue by samuela** [SciML/DifferentialEquations.jl#677]
I'm on julia 1.5.1 and `[0c46a032] DifferentialEquations v6.15.0`.

Consider the following code snippet:
```julia
import DifferentialEquations: solve, ODEProblem, ContinuousCallback

# [pos, vel] = u, and there's a wall at pos = 0.
condition(u, t, integrator) = u[1]
affect!(integrator) = begin
    @error "affect"
    integrator[2] *= -1
end
cb = ContinuousCallback(condition, affect!)
solve(ODEProblem((u, _, _) -> [u[2], 0], [0.75, -1], (0.0, 10.0)), cb = cb)
```
It should hit the ContinuousCallback at t = 0.75, but in fact the callback never fires:
```
julia> include("difftaichi/callback_hell.jl")
retcode: Success
Interpolation: automatic order switching interpolation
t: 3-element Array{Float64,1}:
  0.0
  1.060836786574548
 10.0
u: 3-element Array{Array{Float64,1},1}:
 [0.75, -1.0]
 [-0.31083678657454783, -1.0]
 [-9.249999999999998, -1.0]
```
even though `u[1]` crosses from positive to negative. (I also confirmed the same behavior going from negative to positive.)

**Comment by ChrisRackauckas** [comment]
`solve(ODEProblem((u, _, _) -> [u[2], 0], [0.75, -1], (0.0, 10.0)), callback = cb)`

**Comment by samuela** [comment]
Oh, I'm a ding dong. What's the `cb` keyword argument doing then?

**Comment by ChrisRackauckas** [comment]
Nothing. There's an extra splat that's been their since the dawn of time, and it would be good to go around the SciML repos and make sure nothing uses it and delete the extra splat since this is a known user trap.
