### ISSUE TITLE
Implicit solvers crash when solving an ODE system that contain a Dierckx spline

### ISSUE THREAD

**Issue by wg030** [SciML/DifferentialEquations.jl#678]
I figured that using an implicit solver like TRBDF2 to solve an ode system which contains a Dierckx spline in the definition of the right hand side, the sovler will always crash with
`MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.UJacobianWrapper{ODEFunction{true,typeof(lorenz!),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters},Float64},Float64,3})`.

I have created a MWE modifying the lorenz equation example of the official documentation:

```julia
using Dierckx
using DifferentialEquations

u3 = [0.0, 1.0]
y = [28.0, 27.0]
spl = Spline1D(u3, y, k=1, bc="extrapolate") # y = 28.0 - u3

function lorenz!(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 #du[2] = u[1]*(28.0-u[3]) - u[2] # original
 du[2] = u[1]*spl(u[3]) - u[2] # mod with spline
 du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem( lorenz!, u0, tspan)
sol = solve( prob, Tsit5())
sol2 = solve( prob, TRBDF2())
```

**Comment by ChrisRackauckas** [comment]
Dierckx is not automatic differentiable, so you'll need to do `sol2 = solve( prob, TRBDF2(autodiff=false))`

**Comment by wg030** [comment]
Ok, that's new to me. Thank you very much for the explanation, Chris.
