### ISSUE TITLE
Issue calling solve on a DDEProblem

### ISSUE THREAD

**Issue by gbaraldi** [SciML/DifferentialEquations.jl#684]
While doing the juliacon workshop I found the error in the .txt, it begins like:
```julia
ERROR: MethodError: objects of type AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64} are not callable 
```
I didn't paste the whole error because it is massive. 

This is the code I am using:

```julia
using DifferentialEquations
using Plots

τ = 1.0
function latka_volterra!(du,u,h,p,t)
    🐰, 🐺 = u
    🕥🐰 = h(p,t-τ;idxs=1)
    α,β,γ,δ = p
    du[1] = d🐰 = α*🕥🐰 - β*🐺*🐰
    du[2] = d🐺 = γ*🐺*🐰 -δ*🐺 
    nothing
end
uₒ = [1.0,1.0]
tspan = (0.0, 10.0)
h(p,t) = [1.0,1.0]
h(p,t;idxs = 1) = 1.0
p = [1.5,1.0,3.0,1.0]
prob = DDEProblem(latka_volterra!,uₒ,h,tspan,p,constant_lag = [τ] )

sol = solve(prob)
```
Changing the solve line to this makes it work just fine:
```julia 
sol = solve(prob, MethodOfSteps(Tsit5()))
```
I am using `DifferentialEquations v6.15.0`
This is the version of julia that I am using:
```julia
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "/usr/share/code/code"
  JULIA_NUM_THREADS = 4
```

[error.txt](https://github.com/SciML/DifferentialEquations.jl/files/5375336/error.txt)

**Comment by ChrisRackauckas** [comment]
@YingboMa this is from the change to the autoswitch algorithm caching. Since it now it doesn't detect `MethodOfSteps(AutoTsit5(...))` as an autoswitching algorithm, it ends up not building the cache for it and failing. We need to find some way nice to make this all trait-based, or at least dig another level deeper.
