### ISSUE TITLE
Decoupling tspan and initial time, t0

### ISSUE THREAD

**Issue by BuddhiLW** [SciML/DifferentialEquations.jl#705]
I'm faced with a problem, which is the following: I want to represent a solution, in which (t0,$\ni$) is given. Let's say, (t0,$\ni$) = (0,1). But, I would like to see the graph represented in the hole (-1,1) dominium.

As the tspan is intrinsically related with my t0, how can I make the solver resolve my problem for the given t0, differing the initial value in the interval in tspan?

So, in the given example, I would like to observe the ODE in (-0.88, 0.88), but to solve the problem with condition (t0, y0) = (0,1).

#### Ex8(c)

```jl
using DifferentialEquations
using Plots

function example2!(dy, y, t, p)
    c1  = p
    dy[1] = c1 * y[1]^3
end

y0 = [1]
p = [1]
tspan = (0, 0.88)
prob2 = ODEProblem(example2!, y0, tspan, p)
sol2 = solve(prob2)

plot(sol2)
```

Gratefully,
Pedro G. Branquinho

**Comment by BuddhiLW** [comment]
Related to this problem, how do I represent a function with continuities?

for example y' = 2/(t²-1), will have a valid interval solution for the following intervals:
I1: -inf < t < -1
I2: -1< t <1
l3: 1< t <inf

Of course, in this case I can find easily the analytical solution. But, I would like to computer it, through a hole interval tspan = (-2,2), which steps on both discontinuities, without getting a error.

```jl
using DifferentialEquations
using Plots

function example3!(dy, y, t, p)
    c1 = p
    dy[1] = c1 / (t^2 - 1)
end

y0 = [2/3]
p = [2]
tspan = (-2, -2)
prob3 = ODEProblem(example3!, y0, tspan, p)
sol3 = solve(prob3)

plot(sol2, layout=1)

################

sol2 = solve(prob2)
ERROR: MethodError: no method matching ^(::Array{Float64,1}, ::Int64)
Closest candidates are:
  ^(::Regex, ::Integer) at regex.jl:729
  ^(::Missing, ::Integer) at missing.jl:155
  ^(::Missing, ::Number) at missing.jl:115
 ``

**Comment by ChrisRackauckas** [comment]
So you just want to plot it reflected along the y axis?

**Comment by BuddhiLW** [comment]
(1) I would like to explicitly control my t0, without it being the first value in tspan, because I would like to plot the solution for arbitrary values - just as if I had an analytical solution.

(2): I would like to plot in intervals which may have discontinuities, without errors; maybe limiting a range of values for y calculation. Because most times I don't know where the discontinuities are. Actually, that's what I try to understand qualitatively.

**Comment by ChrisRackauckas** [comment]
(1) you can use the tspan in plot, i.e. `plot(sol,tspan=(0.2,0.6))`.

(2) `ylim` in the plot? This is all documented in the plotting package.

**Comment by BuddhiLW** [comment]
(1) But if I defined my tspan in ODEProble(tspan...), being a subdomain of the area I want to plot?

So, the tspan in my ODEProblem is (0, 2). But, I want to see the solution in (-2,2)? 

(2) The error I have is prior to the plot. It's on 

```jl
sol3 = solve(prob3)
```

If I change the domain to (-2, -0.2) it won't throw me an error. Because there it no y->infinity.

I guess it's not, firstly, a plotting issue, but a I don't know how to make the solver "characterize it's a discontinuity and just calculate y values to a limit"

**Comment by BuddhiLW** [comment]
Pratically, what I would like to write is:

```jl
y0 = [0, -2] ## (t0,y0) = (0,-2)
p = [2]
tspan = (-2, -2)
prob3 = ODEProblem(example3!, y0, tspan, p)
sol3 = solve(prob3)

plot(sol3, layout=1)
 ```

**Comment by BuddhiLW** [comment]
Here, I tried to isolate the discontinuities. Ideally, I imagine I don't have that information _à priori_.

Furthermore, the solutions in (0.2, 1.8) and (2.2, 4) do not represent the solution I'm trying to understand. Because, t0 in (0.2, 1.8) is 0.2. And, t0 in (2.2, 4) is 2.2. 

Can I decouple this behavior? 

```jl
###############
using ModelingToolkit, OrdinaryDiffEq
# using Plots;

@parameters c1 t
@variables y1(t) t
@derivatives D'~t

eqs = [D(y1) ~ c1/(t^2 - 1)]

sys = ODESystem(eqs)
sys = ode_order_lowering(sys)

u0 = [y1 => 2/3]

p  = [c1 => 2]

tspan = (-2, -0.8)
tspan2 = (0.2, 1.8)
tspan3 = (2.2, 4)

prob = ODEProblem(sys,u0,tspan,p,jac=true)
prob2 = ODEProblem(sys,u0,tspan2,p,jac=true)
prob3 = ODEProblem(sys,u0,tspan3,p,jac=true)

sol = solve(prob,Tsit5(), abstol=1e-8, reltol=1e-8)
sol2 = solve(prob2,Tsit5(), abstol=1e-8, reltol=1e-8)
sol3 = solve(prob3,Tsit5(), abstol=1e-8, reltol=1e-8)


p = plot(sol)
p2 = plot(sol2)
p3 = plot(sol3)

plot(p, p2, p3, layout = 1,1,1)
```

**Comment by ChrisRackauckas** [comment]
I don't see the issue? When you clean up the code it runs and plots fine?

```julia
using DifferentialEquations
using Plots

function example3!(dy, y, t, p)
    c1 = p
    dy[1] = c1 / (t^2 - 1)
end

y0 = [2/3]
p = 2.0
tspan = (-2.0, 2.0)
prob3 = ODEProblem(example3!, y0, tspan, p)
sol3 = solve(prob3)

plot(sol3)
savefig("plot.png")
```

![plot](https://user-images.githubusercontent.com/1814174/102802650-fdef6200-4384-11eb-826d-41578016fba8.png)

**Comment by BuddhiLW** [comment]
Put the initial condition y0 = -2, because t0=0 => y0=-2. Can you plot it?

**Comment by ChrisRackauckas** [comment]
This is an integral not an ODE. Why is it not using Quadrature.jl?

**Comment by BuddhiLW** [comment]
I could find the analytical solution, indeed, by integrating. But, It's not always the case. I'm trying to resolve the trivial cases before. 

I can't get this plot (of the analytical solution), by the numeric method of Julia.
phi analytical is, log(|t-1|/|t+1|) 

![pic-selected-201221-1433-31](https://user-images.githubusercontent.com/59554283/102805269-ba532300-4399-11eb-81c9-aa996480bd02.png)

**Comment by BuddhiLW** [comment]
The original problem:

![f1](https://user-images.githubusercontent.com/59554283/102805638-49603b00-439a-11eb-8390-40f390eb4757.jpeg)
![f2](https://user-images.githubusercontent.com/59554283/102805654-4f561c00-439a-11eb-8c49-225216b458c0.jpeg)

My next problem could be considered also an Integration problem... But, further in the book, there will be no space to this problem - discontinuities in ODE Systems.

![f3](https://user-images.githubusercontent.com/59554283/102805670-54b36680-439a-11eb-83dc-fb3cf8ad15fa.jpeg)

**Comment by ChrisRackauckas** [comment]
These methods will not handle divergent trajectories. That would need to come in the future.

**Comment by ChrisRackauckas** [comment]
For reference, the correct code for you problem was:

```julia
using DifferentialEquations
using Plots

function example3!(dy, y, p, t)
    c1 = p
    dy[1] = c1 / (t^2 - 1)
end

y0 = [-2.0]
p = 2.0
tspan = (-2.0, 2.0)
prob3 = ODEProblem(example3!, y0, tspan, p)
sol3 = solve(prob3)

plot(sol3)
savefig("plot.png")
```

You had a ton of errors in your original code.

**Comment by BuddhiLW** [comment]
Alright, that's ok.

But, still, could I decouple the tspan and (t0,y0) condition, to, at least, surround my plot around the divergent points?

I would like to use one initial condition to define the problem for every interval.

The plots show how for each tspan, he coupled the t0 with that interval.

I.e., in the first plot he considered (t0,y0) = (-2.0, -2,0); in the second (t0,y0)= (0.2, -2); third, (t0,y0) = (2.2, -2), as is visible by the plot.



```jl
using DifferentialEquations
using Plots

function example3!(dy, y, p, t)
    c1 = p
    dy[1] = c1 / (t^2 - 1)
end

y0 = [-2.0]
p = 2.0

tspan = (-2.0, -0.2)
tspan2 = (0.2, 1.8)
tspan3 = (2.2, 4)

prob = ODEProblem(example3!, y0, tspan, p)
prob2 = ODEProblem(example3!, y0, tspan2, p)
prob3 = ODEProblem(example3!, y0, tspan3, p)

sol = solve(prob)
sol2 = solve(prob2)
sol3 = solve(prob3)


p = plot(sol)
p2 = plot(sol2)
p3 = plot(sol3)

plot(p, p2, p3, layout = 3)
savefig("plot.png")
```
![plot](https://user-images.githubusercontent.com/59554283/102808685-795e0d00-439f-11eb-8a0c-0d109d5fcfce.png)

**Comment by BuddhiLW** [comment]
Thank you for your time

**Comment by ChrisRackauckas** [comment]
Yes, you can still decouple the solves and piece together the plots. How to do the plotting is a question for discourse.julialang.org.
