### ISSUE TITLE
An error occurred  in SDE problem with Complex number

### ISSUE THREAD

**Issue by syoub8** [SciML/DifferentialEquations.jl#713]
I am implementing a non-diagonal SDE problem with complex values.
  But I faced an error. Here's a code which gives a similar error:
```julia
using DifferentialEquations
f(du,u,p,t) = du .= 1.01u
function g(du,u,p,t)
  du[1,1] = 0.3u[1]
  du[1,2] = 0.6u[1]
  du[2,1] = 1.2u[1]
  du[2,2] = 0.2u[2]
end
prob = SDEProblem(f,g,[1.0,1.0+1.0im],(0.0,1.0),0.0,noise_rate_prototype=zeros(2,2))
dt=1.0e-3
sol = solve(prob,SRA1(),dt=dt)
```
fails with
> InexactError: Float64(0.2 + 0.2im)
> 
> Stacktrace:
>  [1] Real at ./complex.jl:37 [inlined]
>  [2] convert at ./number.jl:7 [inlined]
>  [3] setindex! at ./array.jl:849 [inlined]
>  [4] g(::Array{Float64,2}, ::Array{Complex{Float64},1}, ::Float64, ::Float64) at ./In[38]:7
>  [5] perform_step!(::StochasticDiffEq.SDEIntegrator{SRA1,true,Array{Complex{Float64},1},Complex{Float64},Float64,Float64,Float64,Float64,Float64,Complex{Float64},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_BRIDGE),true,ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{Float64},Nothing,RandomNumbers.Xorshifts.Xoroshiro128Plus},Nothing,Array{Complex{Float64},1},RODESolution{Complex{Float64},2,Array{Array{Complex{Float64},1},1},Nothing,Nothing,Array{Float64,1},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_BRIDGE),true,ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{Float64},Nothing,RandomNumbers.Xorshifts.Xoroshiro128Plus},SDEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,Float64,Nothing,SDEFunction{true,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Array{Float64,2}},SRA1,StochasticDiffEq.LinearInterpolationData{Array{Array{Complex{Float64},1},1},Array{Float64,1}},DiffEqBase.DEStats},StochasticDiffEq.SRA1Cache{Array{Float64,1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Float64,2}},SDEFunction{true,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Nothing,StochasticDiffEq.SDEOptions{Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,Base.Order.ForwardOrdering},DataStructures.BinaryHeap{Float64,Base.Order.ForwardOrdering},Nothing,Nothing,Int64,Float64,Float64,Complex{Float64},Tuple{},Tuple{},Tuple{}},Nothing,Complex{Float64},Nothing,Nothing}, ::StochasticDiffEq.SRA1Cache{Array{Float64,1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Float64,2}}, ::Function) at /home/user/.julia/packages/StochasticDiffEq/nvQku/src/perform_step/sra.jl:53
>  [6] perform_step! at /home/user/.julia/packages/StochasticDiffEq/nvQku/src/perform_step/sra.jl:51 [inlined]
>  [7] solve!(::StochasticDiffEq.SDEIntegrator{SRA1,true,Array{Complex{Float64},1},Complex{Float64},Float64,Float64,Float64,Float64,Float64,Complex{Float64},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_BRIDGE),true,ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{Float64},Nothing,RandomNumbers.Xorshifts.Xoroshiro128Plus},Nothing,Array{Complex{Float64},1},RODESolution{Complex{Float64},2,Array{Array{Complex{Float64},1},1},Nothing,Nothing,Array{Float64,1},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.INPLACE_WHITE_NOISE_BRIDGE),true,ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{Float64},Nothing,RandomNumbers.Xorshifts.Xoroshiro128Plus},SDEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,Float64,Nothing,SDEFunction{true,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Array{Float64,2}},SRA1,StochasticDiffEq.LinearInterpolationData{Array{Array{Complex{Float64},1},1},Array{Float64,1}},DiffEqBase.DEStats},StochasticDiffEq.SRA1Cache{Array{Float64,1},Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Float64,2}},SDEFunction{true,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Nothing,StochasticDiffEq.SDEOptions{Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,Base.Order.ForwardOrdering},DataStructures.BinaryHeap{Float64,Base.Order.ForwardOrdering},Nothing,Nothing,Int64,Float64,Float64,Complex{Float64},Tuple{},Tuple{},Tuple{}},Nothing,Complex{Float64},Nothing,Nothing}) at /home/user/.julia/packages/StochasticDiffEq/nvQku/src/solve.jl:573
>  [8] #__solve#99 at /home/user/.julia/packages/StochasticDiffEq/nvQku/src/solve.jl:7 [inlined]
>  [9] #solve_call#447 at /home/user/.julia/packages/DiffEqBase/DmhWL/src/solve.jl:65 [inlined]
>  [10] solve_up(::SDEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,Float64,Nothing,SDEFunction{true,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Array{Float64,2}}, ::Nothing, ::Array{Complex{Float64},1}, ::Float64, ::SRA1; kwargs::Base.Iterators.Pairs{Symbol,Float64,Tuple{Symbol},NamedTuple{(:dt,),Tuple{Float64}}}) at /home/user/.julia/packages/DiffEqBase/DmhWL/src/solve.jl:86
>  [11] #solve#448 at /home/user/.julia/packages/DiffEqBase/DmhWL/src/solve.jl:74 [inlined]
>  [12] top-level scope at In[38]:11
>  [13] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091

Though the type of the input u of the function g is Array{Complex{Float64},1}, the type of du in the function g is supposed to be Array{Float64,1} by the solver. How do we implement the non-diagonal SDE problem for complex number? Thanks.

**Comment by devmotion** [comment]
It works if you specify the `noise_rate_prototype` (i.e., ["a prototype type instance for [...] the output of `g`"](https://diffeq.sciml.ai/stable/types/sde_types/#Fields)) correctly:
```julia
prob = SDEProblem(f,g,[1.0,1.0+1.0im],(0.0,1.0),0.0,noise_rate_prototype=zeros(Complex{Float64}, 2,2))
```

**Comment by syoub8** [comment]
It works by following your comment. Thank you a lot!
