### ISSUE TITLE
How to inquire the automatically selected algorithm?

### ISSUE THREAD

**Issue by MartinOtter** [SciML/DifferentialEquations.jl#714]
If no algorithm is given, DifferentialEquations selects an algorithm automatically. How to inquire which algorithm was selected?

**Comment by ChrisRackauckas** [comment]
`sol.alg`

**Comment by MartinOtter** [comment]
```
sol.alg = OrdinaryDiffEq.CompositeAlgorithm{Tuple{OrdinaryDiffEq.Vern9,OrdinaryDiffEq.Rodas5{0,false,DiffEqBase.DefaultLinSolve,DataType}},OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Vern9,OrdinaryDiffEq.Rodas5{0,false,DiffEqBase.DefaultLinSolve,DataType},Rational{Int64},Int64}}((OrdinaryDiffEq.Vern9(false), OrdinaryDiffEq.Rodas5{0,false,DiffEqBase.DefaultLinSolve,DataType}(DiffEqBase.DefaultLinSolve(nothing, nothing), Val{:forward})), OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Vern9,OrdinaryDiffEq.Rodas5{0,false,DiffEqBase.DefaultLinSolve,DataType},Rational{Int64},Int64}(-17, OrdinaryDiffEq.Vern9(false), OrdinaryDiffEq.Rodas5{0,false,DiffEqBase.DefaultLinSolve,DataType}(DiffEqBase.DefaultLinSolve(nothing, nothing), Val{:forward}), false, 10, 3, 9//10, 9//10, 2, false))
```
It seems that sol.alg are the algorithm candidates, but the question is which algorithm was used for the simulation.

**Comment by ChrisRackauckas** [comment]
That's the algorithm. The algorithm you got was a composite Vern9 + Rodas5, with choices `sol.alg_choice`.

**Comment by MartinOtter** [comment]
Assume that a user wants to utilize the automatically chosen algorithm directly as an algorithm. For this, I printed (after updating to the newest DifferentialEquations version v6.16.0):
```
@show typeof(sol.alg)
@show sol.alg_choice
```
resulting in the output
```
typeof(sol.alg) = OrdinaryDiffEq.CompositeAlgorithm{Tuple{OrdinaryDiffEq.Vern7,OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.DefaultLinSolve,DataType}},OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Vern7,OrdinaryDiffEq.Rodas4{0,false,DiffEqBase.DefaultLinSolve,DataType},Rational{Int64},Int64}}
sol.alg_choice = [1]
```

It is not clear to me, how to construct the alg argument of `solve(problem,alg)` from this information (or maybe this is not possible in a simple way)?

**Comment by ChrisRackauckas** [comment]
`solve(problem,AutoVern7(Rodas4()))`.

https://diffeq.sciml.ai/stable/solvers/ode_solve/#Pre-Built-Stiffness-Detecting-and-Auto-Switching-Algorithms

If you have `save_everystep=true`, then `alg_choice` is a timeseries that saves which method was used in each step.

**Comment by MartinOtter** [comment]
Thanks.
