### ISSUE TITLE
mean not defined (MonteCarloMeasurements)

### ISSUE THREAD

**Issue by MartinOtter** [SciML/DifferentialEquations.jl#722]
When simulating a model with the following packages with Julia 1.6.0-Beta,
```
  [0c46a032] DifferentialEquations v6.16.0
  [0987c9cc] MonteCarloMeasurements v0.10.0
```
 the following error appears:
```
ERROR: LoadError: UndefVarError: mean not defined
Stacktrace:
  [1] ODE_DEFAULT_NORM
    @ home\.julia\packages\DiffEqBase\zvPvY\src\init.jl:134 [inlined]
```

Line 134 is here:
```
  @require MonteCarloMeasurements="0987c9cc-fe09-11e8-30f0-b96dd679fdca" begin

    promote_u0(u0::AbstractArray{<:MonteCarloMeasurements.AbstractParticles},p::AbstractArray{<:MonteCarloMeasurements.AbstractParticles},t0) = u0
    promote_u0(u0,p::AbstractArray{<:MonteCarloMeasurements.AbstractParticles},t0) = eltype(p).(u0)

    value(x::Type{MonteCarloMeasurements.AbstractParticles{T,N}}) where {T,N} = T
    value(x::MonteCarloMeasurements.AbstractParticles) = mean(x)

    @inline fastpow(x::MonteCarloMeasurements.AbstractParticles, y::MonteCarloMeasurements.AbstractParticles) = x^y

    # Support adaptive steps should be errorless
    @inline function ODE_DEFAULT_NORM(u::AbstractArray{<:MonteCarloMeasurements.AbstractParticles,N},t) where {N}
      sqrt(mean(x->ODE_DEFAULT_NORM(x[1],x[2]),zip((value(x) for x in u),Iterators.repeated(t))))  # <--- line 134
    end
```

When simulating with Julia 1.5.2, and the same versions of the two packages as above, this issue does not occur.

It seems however, that different versions of OrdinaryDiffEq are used:

- with Julia 1.6.0-beta:  DiffEqBase v6.55.0
- with Julia 1.5.2: DiffEqBase v6.44.3

The code in init.jl looks exactly the same for me in the two DiffEqBase versions (so I am confused).

I wonder whether the code above (line 134) should be 
```
sqrt(MonteCarloMeasurements.mean(x...
```

**Comment by MartinOtter** [comment]
I added DiffEqBase v6.44.3 explicitly in Julia 1.6.0-beta and simulated again: The problem does not occur. So the issue is DiffEqBase v6.44.3 with respect to v6.55.0. However, v6.44.3, downgrades 10 ore more packages, so the reason could also be the combination.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/DiffEqBase.jl/commit/9b1a8d32ab4a9a2e9a1902bb34803d2571faeb04
