### ISSUE TITLE
FunctionMap using enum is broken

### ISSUE THREAD

**Issue by sdwfrost** [SciML/DifferentialEquations.jl#734]
Hi!

It looks like the refactoring to using Symbolics has broken my FunctionMap model that uses enums:

This is the old working example:

[https://github.com/epirecipes/sir-julia/blob/master/markdown/abm_vector_diffeq/abm_vector_diffeq.md](https://github.com/epirecipes/sir-julia/blob/master/markdown/abm_vector_diffeq/abm_vector_diffeq.md)

I now get:

```julia
sol_abm = solve(prob_abm,
    solver = FunctionMap(),
    dt = δt,
    callback = cb,
    dense = false,
    save_on = false);

Error: MethodError: no method matching zero(::Type{Main.##WeaveSandBox#286.
InfectionStatus})
Closest candidates are:
  zero(!Matched::Type{Symbolics.TermCombination}) at /home/simon/.julia/pac
kages/Symbolics/ZuF87/src/linearity.jl:67
  zero(!Matched::Type{Missing}) at missing.jl:103
  zero(!Matched::Type{LibGit2.GitHash}) at /buildworker/worker/package_linu
x64/build/usr/share/julia/stdlib/v1.5/LibGit2/src/oid.jl:220
  ...
```

**Comment by ChrisRackauckas** [comment]
The link is broken. Which one is that example?

I think you just locally need `Base.zero(::Type{InfectionStatus}) = Infected` or something of the sort.

**Comment by ChrisRackauckas** [comment]
Better fix is in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1362
