### ISSUE TITLE
Delay Differential Equations / MethodError

### ISSUE THREAD

**Issue by ChrisNabold** [SciML/DifferentialEquations.jl#736]
julia> using DifferentialEquations, Plots
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

julia> const r = 1.0; const K = 1.0, const tau = 1.0
(1.0, 1.0)

julia> function func(t,u,h,du)
       du = r*u*h(t-tau)K
       end
func (generic function with 1 method)

julia> lags = tau
1.0

julia> h(t) = 1.0
h (generic function with 1 method)

julia> tspan = (0.0, 100.0)
(0.0, 100.0)

julia> u0 = 0.0
0.0

julia> p = tau
1.0

julia> prob = DDEProblem(func,u0,h,tspan; constant_lags=lags)
DDEProblem with uType Float64 and tType Float64. In-place: false
timespan: (0.0, 100.0)
u0: 0.0

julia> alg = MethodOfSteps(Tsit5())
MethodOfSteps{Tsit5,NLFunctional{Rational{Int64},Rational{Int64}},false}(Tsit5(), NLFunctional{Rational{Int64},Rational{Int64}}(1//100, 1//5, 10))

julia> sol = solve(prob,alg)
ERROR: MethodError: objects of type SciMLBase.NullParameters are not callable
Stacktrace:
 [1] func(::Float64, ::Function, ::SciMLBase.NullParameters, ::Float64) at .\REPL[2]:2

I got stuck with this example - Can anyone help me to find the error. Thank you

**Comment by devmotion** [comment]
Your function signature is incorrect, `func` should be of the form `func(du, u, h, p, t)` and `h` of the form `h(p, t)`. You can find some more explanations in the documentation, e.g., https://diffeq.sciml.ai/stable/types/dde_types/#Mathematical-Specification-of-a-DDE-Problem and https://diffeq.sciml.ai/stable/tutorials/dde_example/.

**Comment by anandijain** [comment]
thanks, could you maybe make the code block something I can copy paste?
ive done it for you this time but this is a better way to get help:
```julia 
using DifferentialEquations, Plots
const r = 1.0; const K = 1.0, const tau = 1.0
function func(t, u, h, du)
    du = ruh(t - tau)K
end
lags = tau
h(t) = 1.0
tspan = (0.0, 100.0)
u0 = 0.0
p = tau
prob = DDEProblem(func, u0, h, tspan; constant_lags=lags)
alg = MethodOfSteps(Tsit5())
sol = solve(prob, alg)
```

As for the actual issue, there are a few things I noticed. If you read the docs on [DDEs](https://diffeq.sciml.ai/stable/tutorials/dde_example/), you'll notice that your `func` does not put the args in the correct order.  `function func(du, u, h, p, t)` is how it is in the docs.
The other thing missing is that `p=DiffEqBase.NullParameters()` in the doc example. 

This doesn't work, but is closer to the answer, sorry I couldn't fix the whole thing. I believe there is a problem with your `h` function. In the docs it has two args.
```julia
using DifferentialEquations, Plots
const r = 1.0; const K = 1.0, const tau = 1.0

function func(du, u, h, p, t)
    du[1] = r*u[1]*h(t - tau)*K
end
lags = tau
h(p, t) = 1.0
tspan = (0.0, 100.0)
u0 = 0.0
p = tau
prob = DDEProblem(func, [u0], h, tspan, p=DiffEqBase.NullParameters(); constant_lags=lags)
alg = MethodOfSteps(Tsit5())
sol = solve(prob, alg)
```
@devmotion  beat me to it.

**Comment by ChrisRackauckas** [comment]
>The other thing missing is that p=DiffEqBase.NullParameters() in the doc example.

You don't need to write the default args.

**Comment by ChrisNabold** [comment]
Dear Anand

I am trying for several days to solve the problem, so I give you the last input in EX8.7b

I am really very grateful for your help

 

Thank you

**Comment by anandijain** [comment]
this code works:
```julia

using DifferentialEquations, Plots

function func!(du, u, h, p, t)
    r, K, tau = p # scalars 
    hist = h(p, t - tau) # scalar
    du[1] = r * u[1] * hist * K
    nothing
end

h(p,t) = 1.0
tau = 1.0
lags = tau
r = 1.0; K = 1.0

p =[r, K, tau]
tspan = (0.0, 100.0)
u0 = [0.0]

prob = DDEProblem(func, u0, h, tspan, p; constant_lags=lags)
alg = MethodOfSteps(Tsit5())

sol = solve(prob, alg)
```
Happy to help!

**Comment by devmotion** [comment]
Unfortunately, @anandijain's solution and the comments therein are not correct. `h(p, t)` returns the old state of the system at time `t`. Thus it does not return a scalar in your example but a vector with one element (and although it seems to work to define `h(p, t) = 1.0` you should really define `h(p, t) = [1.0]` for the state before the initial time point - otherwise also the automatic determination of the order of the discontinuity at the initial time point will be incorrect).

The following is a correct implementation:
```julia
using DelayDiffEq

function f(du, u, h, p, t)
    r, K, tau = p
    uold = h(p, t - tau)
    du[1] = r * u[1] * uold[1] * K
    nothing
end

h(p, t) = [1.0]
r = 1.0
K = 1.0
tau = 1.0

p = (r, K, tau)
tspan = (0.0, 100.0)
u0 = [0.0]

prob = DDEProblem(f, u0, h, tspan, p; constant_lags=(tau,))

sol = solve(prob, MethodOfSteps(Tsit5()))
```

Please check the documentation for additional information, in particular the two links I posted above should be helpful. E.g., it is explained there how you could define and call the history function with an `idxs` keyword argument such that it actually returns a scalar.

**Comment by ChrisNabold** [comment]
Dear Anand,

 

Thank you for your help. I tried it with your Input but I still receive an error in sol=solve(prob, alg)

Error: MethodError: Cannot convert  ‘convert’ an object of type Array(Float64,1) to an object of type Float64

PS I changed the statement prob= prob = DDEProblem(func!, u0, h, tspan, p; constant_lags=lags)
 
If you can run the example I probable have an error with DifferentialEquations.jl (I use DifferentialEquations v6.16.0)
 
I wish you a nice weekend – and thank you for your help
Chris Nabold

**Comment by anandijain** [comment]
@devmotion dang you! i *just* got it working 😆 thanks!

**Comment by ChrisNabold** [comment]
Thank you for all who helped to get the problem to run.

**Comment by freemin7** [comment]
This issue can be closed now i guess
