### ISSUE TITLE
Use Autovern9 and Rodas5 became slow when meet instability and maxiters needed

### ISSUE THREAD

**Issue by Undi123** [SciML/DifferentialEquations.jl#739]
Hey dear developer and @ChrisRackauckas 
I used input parameters generated randomly in a designed search range for my ODE functions. My ODE system is between stiff and non-stiff based on the parameter generated. When using for loops, most of the time the solver needs less than 300ms to obtain solution. But sometimes it would cost an extremely large time (>300s) to obtain solution when the solution.retcode is MaxIters. I don't know what the solver is doing when it cost a huge time. How can I minimize this time-consuming procedure? 

The code I wrote is using Particle Swarm Optimization (PSO) to solve an inverse modeling problem. The parameters are generated randomly in search space for my ODE systems. The PSO could minimize the error between the ODE solution and experimental data to find the fittest parameters. To minimize the evaluation time when the problem is unstable or needs larger maxiters, I have set the maxiter to be 1e3. But when some improper parameter is generated and put into solver, it would like the program is crashed. To my surprise, when I print this strange parameters and test in global. The solver would rum normally and cost less time (less than 1s) comparing in for loop. So I want to know why in for loop, the warning "Larger maxiters is needed" cost extremely huge time. 

When I interrupt the program at the moment it cost huge time. The Stacktrace is as follows:
[1] getindex at .\tuple.jl:24 [inlined]
[2] get_current_isfsal at C:\Users\Undi\.julia\packages\OrdinaryDiffEq\la32G\src\alg_utils.jl:48 [inlined]

Can anybody explain why solver slowed down? Thanks a lot.

Wang

The code I wrote is attached below, just run main, please.

[Problem.zip](https://github.com/SciML/DifferentialEquations.jl/files/6294620/Problem.zip)

**Comment by ChrisRackauckas** [comment]
It doesn't matter what the ODE solver is: changing the parameters of a system can drastically change the behavior of the system. Changing a parameter can change it from easy to very not easy, non-stiff to stiff. Changing a parameter can make the analytical solution of an ODE explode to Inf in finite time, or change from a solution that is in real numbers to one that necessarily is non-unique in the real numbers. There are all kinds of things that can happen when a parameter changes, so this is not very uncommon. Did you try one of the slower parameters outside of the optimization and see what it looks like? That will be informative, and may help you set better bounds on the PSO.

Closing since there's nothing actionable here, but feel free to continue the discussion.

**Comment by Undi123** [comment]
Thanks, @ChrisRackauckas. Actually, I don't care about if ODE could be solvable, when it is not solvable we just use 
`if sol.retcode != success, fitness = Inf`. The only problem is sometimes the ODE with improper parameters was quite slow. I don't know why it was so slow. I printed and tried to use those slower parameters outside the main loop of optimization. The solver worked normally with less than 1s although it needs more maxiter. But in optimization, it would cost as long as hundreds of seconds.  That's why I was confused.

**Comment by ChrisRackauckas** [comment]
Could be a GC thing.

**Comment by Undi123** [comment]
Thanks a lot, @ChrisRackauckas. So is there a way to avoid this problem?

**Comment by Undi123** [comment]
I noticed when the mutable struct is used, the GC might slow down the programme. Therefore, I also tried to use multiple arrays to store intermediate data. But this problem still occurs.

**Comment by ChrisRackauckas** [comment]
can you isolate it?

**Comment by Undi123** [comment]
Hey @ChrisRackauckas, I tried to isolate this bug, but I failed. I tried to run those code on another PC with same environment. To my surprise, it worked well. That's weird. Now I used a i7-8700 with 16G ram. I have reinstalled the Win 10. But this problem still presents.

**Comment by Undi123** [comment]
Oh god, I noticed when I use high-performance mode for my PC. This situation has decreased, but the halt will still occur sometimes. That's really weird. Maybe it is related to my hardware. How can I determine which part is wrong?

**Comment by ChrisRackauckas** [comment]
That I don't know 🤷 .

**Comment by Undi123** [comment]
Thanks a lot anyway!

**Comment by novalex98** [comment]
I'm encountering a similar issue.  I'm running code on a high performance computing environment that uses slurm (UW's Hyak supercomputer). I first saw that my code would freeze with no error message after an amount of time that depended on what I set the heap-size-hint to. From there, I followed the suggestion here https://discourse.julialang.org/t/poor-performance-of-garbage-collection-in-multi-threaded-application/75493/7 to use garbage collection. I am using a shooting method to solve a boundary value problem, so the garbage collection call is inside a for loop inside an ODE solver. When I added this I started seeing the error " Warning: Interrupted. Larger maxiters is needed. If you are using an integrator for non-stiff ODEs or an automatic switching algorithm (the default), you may want to consider using a method for stiff equations. See the solver pages for more details (e.g. https://docs.sciml.ai/DiffEqDocs/stable/solvers/ode_solve/#Stiff-Problems).
" which I've never seen before. This test case ran successfully on my PC (and on the HPC computer's login node when I made a mistake... oops)

**Comment by ChrisRackauckas** [comment]
I'm not sure this is related at all. Your example doesn't seem related to autoswitch instability from what I can tell, but you have not shared code so it's impossible to know. Please share an MWE as described in the issue template. 

> UW's Hyak supercomputer

Note I'll be at UW on Tuesday

**Comment by novalex98** [comment]
Dear Dr. Rackauckas,

I'm free Tuesday November 28th from noon to 4 pm or after 5:30 pm. I would greatly appreciate the chance to get you lunch/dinner and ask you some questions, if you have time. You can email me at novalex@uw.edu

**Comment by Undi123** [comment]
Hey, Novalex,
It seems related to the computer you used, when I used a relatively low-performance computer. The program runs well, although it takes more time to compute compared with my workstation.
Besides, you could use a more robust algorithm to solve stiff ODEs like Rodas5 and you need to minimize the appearance of reaching maxiters. This is related to the accuracy you set.
I also noticed this problem would be worse if you used a higher version of Julia like V1.6. It would crash after the freezing of program you mentioned.
The code I used was written in V1.54 or lower, although it might take more time to compute, it won't crash.

**Comment by ChrisRackauckas** [comment]
> Besides, you could use a more robust algorithm to solve stiff ODEs like Rodas5 and you need to minimize the appearance of reaching maxiters. This is related to the accuracy you set.

> I also noticed this problem would be worse if you used a higher version of Julia like V1.6. It would crash after the freezing of program you mentioned.

Do you have an MWE? Note that your issue here was solved back a bit with a separate runtime caching system for the autoswitch awhile back, so anything here should be unrelated.

> I'm free Tuesday November 28th from noon to 4 pm or after 5:30 pm. I would greatly appreciate the chance to get you lunch/dinner and ask you some questions, if you have time. You can email me at [novalex@uw.edu](mailto:novalex@uw.edu)

I'll be at the meetup https://www.eventbrite.com/e/seattle-julia-language-users-tickets-764199620637

**Comment by Undi123** [comment]
Dear Dr. Rackauckas,
Thank you for your insightful comments.
I must admit, it has been almost a year since I last worked with Julia. Therefore, I may need some time to refresh my knowledge.

**Comment by novalex98** [comment]
> > Besides, you could use a more robust algorithm to solve stiff ODEs like Rodas5 and you need to minimize the appearance of reaching maxiters. This is related to the accuracy you set.
> 
> > I also noticed this problem would be worse if you used a higher version of Julia like V1.6. It would crash after the freezing of program you mentioned.
> 
> Do you have an MWE? Note that your issue here was solved back a bit with a separate runtime caching system for the autoswitch awhile back, so anything here should be unrelated.
> 
> > I'm free Tuesday November 28th from noon to 4 pm or after 5:30 pm. I would greatly appreciate the chance to get you lunch/dinner and ask you some questions, if you have time. You can email me at [novalex@uw.edu](mailto:novalex@uw.edu)
> 
> I'll be at the meetup https://www.eventbrite.com/e/seattle-julia-language-users-tickets-764199620637

Registered!
