### ISSUE TITLE
Only trivial solution for in-place definition of ODE RHS

### ISSUE THREAD

**Issue by daharn** [SciML/DifferentialEquations.jl#759]
I hope this is the right place for this:

I am solving a stiff system of ODEs. When I define my right-hand-side function in an in-place way, i. e. `f!(dy,y,p,t)`, I will end up with a constant solution, even if I prescribe very small time steps. However, simply by replacing `f!` with `f(y,p,t)=f!(zero(y),y,p,t)` in my problem definition, I get the desired solution. 

Because I am not sure I can produce a sufficiently general MWE: am I missing an obvious (mathematical) reason for this behavior? It seems independent of the actual choice of the solver. 

EDIT: Here is my MWE with a similar problem. It probably has to do with the fact that I am using the kinetics library cantera via PyCall. In this case, this creates a PyObject as a global variable that links to an underlying C++ object and is accessed throughout the calculation:
```julia
using DifferentialEquations
using PyCall
ct = pyimport("cantera")

# ideal gas constant
const R̄ = ct.gas_constant::Float64

function f!(dy,y,p,t)::Vector{Float64}
    """
    ODE system for an ischoric chemical reactor
    """
    T = y[1]
    Y = y[2:end]

    gas.TDY = T, ρ₀, Y

    Mᵢ = gas.molecular_weights::Vector{Float64}
    ω̇  = gas.net_production_rates::Vector{Float64}

    Ẏ = ω̇ .* Mᵢ ./ ρ₀
    uᵢ = (gas.standard_enthalpies_RT::Vector{Float64} .- 1) .* R̄ .* T ./ Mᵢ
    cᵥ = gas.cv_mass::Float64

    Ṫ = - sum(uᵢ .* Ẏ) ./ cᵥ

    dy = vcat(Ṫ,Ẏ)
end

# non-mutating wrapper
f(y,p,t) = f!(zero(y),y,p,t)

# create cantera solution object (actually C++ object)
gas = ct.Solution("gri30.xml")::PyObject
gas.TPX = 1800, 1e5, "H2:42, O2:21, N2:79"
const ρ₀ = gas.density::Float64

y₀ = vcat(gas.T::Float64, gas.Y::Vector{Float64})

tel = [0,5e-4]

prob = ODEProblem(f,y₀,tel) ### this works
# prob = ODEProblem(f!,y₀,tel) ### this only gives trivial solutions


out = solve(prob, algo_hint=[:stiff],dtmax=1e-5) ### this works
# out = solve(prob,Rosenbrock23(autodiff=false)) ### this works
# out = solve(prob,Rosenbrock23(autodiff=true)) ### this does not work
```

However, it still puzzles me that exchanging the mutating with the non-mutating form changes the behavior of the solver.

As a side note: I suppose the fact that I have to set `autodiff=false` also stems from the usage of PyCall, because the PyObjects can't be differentiated?

**Comment by ChrisRackauckas** [comment]
`dy = vcat(Ṫ,Ẏ)` that's allocating a new vector, not mutating. Using `f(y,p,t)=f!(zero(y),y,p,t` changes to in-place form, so the returned vector `vcat(Ṫ,Ẏ)` is used instead of the original `dy`.

The quick fix is just `dy .= vcat(Ṫ,Ẏ)`, where `.=` means mutate. But in reality, for performance you want to never create the vcat vector and instead mutate the pieces.

**Comment by daharn** [comment]
Thanks a lot for the quick response! Of course that's it! Since this is my first julia project, I should have known it's something obvious... 

Am I at least correct in my assumption about automatic differentiation not working if you use python packages? Or could even that be achieved somehow?

**Comment by ChrisRackauckas** [comment]
>Am I at least correct in my assumption about automatic differentiation not working if you use python packages? Or could even that be achieved somehow?

It could be done: we have a limited form of AD that works on some R packages. For Python, it would need a few difficult integration pieces though... let's just say it would be a fun project.
