### ISSUE TITLE
FAQ suggestion: lazily allocate buffers for use with automatic differentiation

### ISSUE THREAD

**Issue by stevengj** [SciML/DifferentialEquations.jl#769]
As noted [in the FAQ](https://diffeq.sciml.ai/stable/basics/faq/#I-get-Dual-number-errors-when-I-solve-my-ODE-with-Rosenbrock-or-SDIRK-methods), using pre-allocated buffers is problematic for automatic differentiation, because then one sometimes needs a buffer of dual numbers instead.

The FAQ suggests using the undocumented `get_tmp` and `dualcache` functions.   I have to admit that I had a hard time getting these to work in our problem, and the lack of documentation made them somewhat hard to recommend.  (A basic difficulty seems to be choosing the right type parameters for the dual numbers ahead of time.)

It occurred to me that a much simpler solution is to allocate buffers lazily, of the same type as `u`, caching them for later usage.   This worked well for us.   The implementation is easy — perhaps something like this could be included and suggested in the FAQ?
```jl
"""
    b = LazyBufferCache(f=identity)

A lazily allocated buffer object.  Given a vector `u`, `b[u]` returns a `Vector` of the 
same element type and length `f(length(u))` (defaulting to the same length), which is
allocated as needed and then cached within `b` for subsequent usage.
"""
struct LazyBufferCache{F<:Function}
    bufs::Dict # a dictionary mapping types to buffers
    lengthmap::F
    LazyBufferCache(f::F=identity) where {F<:Function} = new{F}(Dict()) # start with empty dict
end

# override the [] method
function Base.getindex(b::LazyBufferCache, u::AbstractVector{T}) where {T}
    n = b.lengthmap(length(u)) # required buffer length
    buf = get!(b.bufs, T) do
        Vector{T}(undef, n) # buffer to allocate if it was not found in b.bufs
    end::Vector{T} # declare type since b.bufs dictionary is untyped
    return resize!(buf, n) # resize the buffer if needed, e.g. if problem was resized
end
```

**Comment by ChrisRackauckas** [comment]
Yes, the `dual_cache` form is very optimized, but it's overkill and can be hard to use sometimes. I've been wanting to move it out to a package, but also secretly hoping that some of the compiler tools like https://github.com/oxinabox/AutoPreallocation.jl would just replace it sooner or later. I kind of think PreallocationTools.jl or something would be a nice package with these tricks. The trick that you show is definitely simpler and more robust, though of course the dynamism would give it troubles in say GPU codegen. It would be good to offer this method as well and fully document the trade-offs. I might get around to finally doing this package over the weekend.

**Comment by ChrisRackauckas** [comment]
Included in https://github.com/SciML/PreallocationTools.jl 🎉
