### ISSUE TITLE
EnsembleThreads does not use multiple cores

### ISSUE THREAD

**Issue by Volker-Weissmann** [SciML/DifferentialEquations.jl#780]
[The documentation](https://diffeq.sciml.ai/stable/features/ensemble/) says that `EnsembleThreads()` uses multithreading:
* `EnsembleThreads()` - The default. This uses multithreading. It's local (single computer, shared memory) parallelism only. Fastest when the trajectories are quick.

But the following starts using multiple cores, then drops down to one core when `starting main simulation` is printed.

```julia
using Distributed
addprocs(4)
import DifferentialEquations
f(du, u, p, t) = du .= 1.
g(du, u, p, t) = du .= 1e-3
prob = DifferentialEquations.SDEProblem(f, g, [0.], (0., 100.))
ensembleprob = DifferentialEquations.EnsembleProblem(prob)
println("starting main simulation")
flush(stdout)
DifferentialEquations.solve(ensembleprob, DifferentialEquations.EnsembleThreads(), trajectories=2^8)
```

See also: https://discourse.julialang.org/t/differentialequations-jl-uses-just-one-core/65916/14

**Comment by ChrisRackauckas** [comment]
```julia
import DifferentialEquations
f(du, u, p, t) = du .= 1.
g(du, u, p, t) = du .= 1e-3
prob = DifferentialEquations.SDEProblem(f, g, [0.], (0., 100.))
ensembleprob = DifferentialEquations.EnsembleProblem(prob)
@time DifferentialEquations.solve(ensembleprob, DifferentialEquations.EnsembleThreads(), trajectories=100000)
```

shows it's working at max capacity and it's just the problem size.
