### ISSUE TITLE
Memory leakage when integrating a simple equation

### ISSUE THREAD

**Issue by zornsllama** [SciML/DifferentialEquations.jl#790]
I was working with the example vector field

```julia
function vf!(du, u,p,t)
    du .= (2 .- u) ./ 3.0 .+ 0.2
end
```
Implementing Forward Euler by hand works fine:

```julia

u0 = rand(10000)
du0 = similar(u0)

function mystep!(du,u)
    vf!(du,u,nothing,nothing)
    u .= u .+ 0.01*du
end

@time for i=1:100000
    mystep!(du0, u0)
end
```

```output
  2.042369 seconds (212.04 k allocations: 7.459 GiB, 6.86% gc time, 1.66% compilation time)
```

```
Total memory usage by Julia process at this point: 485.1 MB
```

 However, if I instead wrap the vector field in an ODEProblem and attempt to Euler step (in place) with the integrator interface, the Julia process fills up memory rapidly seemingly without garbage collecting. 

```julia

using DifferentialEquations

u0 = rand(10000)
tspan = (0.0,1000.0)

prob = ODEProblem(vf!, u0, tspan)

integ = init(prob, Euler(),dt=.01)

@time for i=1:100000
    step!(test)
end
```

```
Total memory usage by Julia process at this point: 5.2 GB
Julia process crashes -- REPL says "Killed"
```

(My laptop is a Thinkpad with 4 GB RAM). The same issue occurs if I only perform 10000 steps with the integrator interface; now Julia doesn't crash, but is using up almost all of my memory. Running `GC.gc()` afterwards doesn't rectify the situation. I am assuming this isn't the desired behavior; have I done something silly/misunderstood something or is there an issue here?

**Comment by ChrisRackauckas** [comment]
The one you did by hand doesn't look like it's saving every step, so it looks like you probably want `integ = init(prob, Euler(),dt=.01,save_everystep=false)`?

**Comment by zornsllama** [comment]
Ah ok, didn't realize the integrator is building a full solution in the background by default. Thanks for the clarification!

**Comment by ChrisRackauckas** [comment]
Yeah its defaults match `solve` and the documented values at https://diffeq.sciml.ai/stable/basics/common_solver_opts/

**Comment by zornsllama** [comment]
In case you happen to see this, one additional quick question. Even after setting `save_everystep = false`, using the integrator interface to Euler step is a bit slower than Euler stepping by hand (~2.7 secs vs ~2 secs on my machine). What exactly is the additional overhead introduced by the integrator interface?
