### ISSUE TITLE
Sundials Failing to Precompile

### ISSUE THREAD

**Issue by Akshaye-Pal** [SciML/DifferentialEquations.jl#795]
Previously had a package with DifferentialEquations working just fine. Then Sundials started to fail during the precompilation. Currently working on a Mac (Catalina 10.15.7) and using Julia Version 1.6.2 (2021-07-14). Tried removing Julia and re-downloading from the main Julia page as someone else had said worked #737, which worked at first then the Sundials precompilation failure came back. Below is the error. I'm new to the community by the way; any help/insight would be much appreciated.

ERROR: LoadError: InitError: could not load library "/Users/user/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib"
dlopen(/Users/user/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib, 1): Library not loaded: @rpath/libsuitesparseconfig.5.4.0.dylib
  Referenced from: /Users/user/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib
  Reason: image not found
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:114
  [2] dlopen (repeats 2 times)
    @ ./libdl.jl:114 [inlined]
  [3] __init__()
    @ Sundials_jll ~/.julia/packages/Sundials_jll/heTyl/src/wrappers/x86_64-apple-darwin14-libgfortran5.jl:422
  [4] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:696
  [5] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:782
  [6] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1020
  [7] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:936
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:923
  [9] include
    @ ./Base.jl:386 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1235
 [11] top-level scope
    @ none:1
 [12] eval
    @ ./boot.jl:360 [inlined]
 [13] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [14] top-level scope
    @ none:1
during initialization of module Sundials_jll
in expression starting at /Users/user/.julia/packages/Sundials/YfkdE/src/Sundials.jl:3
ERROR: LoadError: Failed to precompile Sundials [c3572dad-4567-51f8-b174-8c6c989267f4] to /Users/user/.julia/compiled/v1.6/Sundials/jl_9awidt.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IOContext{Base.PipeEndpoint}, internal_stdout::IOContext{IOStream}, ignore_loaded_modules::Bool)
    @ Base ./loading.jl:1385
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1329
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1043
  [5] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:936
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:923
  [7] include
    @ ./Base.jl:386 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1235
  [9] top-level scope
    @ none:1
 [10] eval
    @ ./boot.jl:360 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [12] top-level scope
    @ none:1
in expression starting at /Users/user/.julia/packages/DifferentialEquations/el96s/src/DifferentialEquations.jl:1

**Comment by ChrisRackauckas** [comment]
Looks like the download may have failed. What happens if you `]build Sundials`?

**Comment by Akshaye-Pal** [comment]
I don't think it does anything, it just returns. I tried re-compiling after executing the command below and Sundials still failed to precompile.

(my_module) pkg> build Sundials

(my_module) pkg>

**Comment by ChrisRackauckas** [comment]
Try deleting your `.julia` and letting it download again?

**Comment by Akshaye-Pal** [comment]
I definitely tried that already, after which it worked fine, then Sundials again gave me this problem. So I'm worried that this precompilation error will just come back again. But I'll delete, download and come back here with what happens. However if it does come back, is there anything from that first error that indicates what's actually causing this? I'm just having a difficult time figuring out what the problem is which is making troubleshooting not easy

**Comment by Akshaye-Pal** [comment]
Unfortunately it failed again. I deleted the `.julia`, downloaded again from the main page (https://julialang.org/downloads/) then generated a test module where I just tried adding `DifferentialEquations`. Got the same error as above.

**Comment by ChrisRackauckas** [comment]
@giordano do you know what could be up?

**Comment by Akshaye-Pal** [comment]
So I just deleted Julia entirely and re-downloaded. I think I had some background Julias running that I did not get rid of properly. Things seem to be ok now. Thanks for the help!
