### ISSUE TITLE
 warning: method definition (:: type {float32}) (base. Ionic {: log π}) in module ionic constants at irrationals. JL

### ISSUE THREAD

**Issue by liushang0322** [SciML/DifferentialEquations.jl#812]
I'm sorry to bother you. When I build my own library, I want to use differential equations in the library, but when I use my own library, there are many warnings, such as: warning: method definition (:: type {float32}) (base. Ionic {: log π}) in module ionic constants at irrationals. JL: 190 overwritten in module statsfuns on the same line (check for duplicate calls to `include`).

** incremental compilation may be fatally broken for this module **。

How can I deal with this problem

**Comment by ChrisRackauckas** [comment]
That's due to an old version of StatsFuns.jl, just update that library or find what's holding it back (this is not holding it back)
