### ISSUE TITLE
ERROR: LoadError: MethodError: no method matching names(::Base.Broadcast.BroadcastFunction{Irrational{:log4π}}) 

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/DifferentialEquations.jl#818]
I am encountering a method error pasted here, while Precompiling DifferentialEquations.jl for v6. 20
https://discourse.julialang.org/t/unable-to-precompile-differentialequations-jl-in-juno-ide-in-new-environment-and-empty-project/71608
I am doing this in a new environment and empty project with julia 1.6.3
What am I missing?

**Comment by ChrisRackauckas** [comment]
Yeah, not much to say there if attempts to recreate it fixed it 😅 . Seems like maybe a Pkg hiccup or something.
