### ISSUE TITLE
How to return a mathmatical expression of predict solution "U_predict"

### ISSUE THREAD

**Issue by Runfa-Zhang** [SciML/DifferentialEquations.jl#819]
# How to return a mathmatical expression of predict solution "U_predict"

Usually the result of predict solution is a Matrix.

But I need PDE's U_predict is a mathmatical expression, just like Exact analytical solution.

So how to return a mathmatical expression of analytical solution.

**Comment by ChrisRackauckas** [comment]
Is this on the wrong repository? I have no idea what's being asked here. Please give more information if there's an issue here.
