### ISSUE TITLE
ask for pytorch version

### ISSUE THREAD

**Issue by dgbsg** [SciML/DifferentialEquations.jl#823]
Hello, I would like to ask whether you are proficient in pytorch. I am trying to write a similar function code block in Pytorch recently, but I seem to be insufficient. Can you help me? Thank you very much.
`using Flux, DiffEqSensitivity, DifferentialEquations
using Distributions, Distances
using DelimitedFiles, Plots
using Random
# model `initialization`
model = Chain(Dense(N+1, 100, tanh), Dense(100, N));
p1, re = Flux.destructure(model);
ps = Flux.params(p1);

# define the CME
function CME(du, u, p, t)
     ρ = 20.0;  
     NN = re(p)(u);   #将神经网络分离参数，与形成神经网络的参数
     du[1] = -ρ*u[1] + NN[1]*u[2];
     for i in 2:N
           du[i] = ρ*u[i-1] + (-ρ - NN[i-1])*u[i] + NN[i]*u[i+1];
     end
     du[N+1] = ρ*u[N] + (-ρ - `NN[N])*u[N+1];`
end

# initialize the ODE solver
u0 = [1.; zeros(N)]; 
tspan = (0.0, 50.0);
problem = ODEProblem(CME, u0, tspan, p1);

# define the objective function
function loss_adjoint()
      # solve ODE problem and save at the selected time
      sol = Array(solve(problem, Tsit5(), u0=u0, p=p1, saveat=[4,8,14,20,26,32,38,44,50]));
      # calculate MSE at the selected time between train data and fitted data
      Flux.mse(sol, train_sol[:, [3,5,8,11,14,17,20,23,26]])

end
print(size(train_sol[:, [3,5,8,11,14,17,20,23,26]]))
######
@time Flux.train!(loss_adjoint, ps, Iterators.repeated((), 7), ADAM(0.25))
@time Flux.train!(loss_adjoint, ps, Iterators.repeated((), 8), ADAM(0.12))
@time Flux.train!(loss_adjoint, ps, Iterators.repeated((), 2), ADAM(0.02))
`

**Comment by ChrisRackauckas** [comment]
Ehh this isn't an issue. You can ask on the Discourse or Slack, but there's nothing in this library to do here. Just use that code if that's what you want.
