### ISSUE TITLE
Number of jacobians created | Influence generation of new jacobian

### ISSUE THREAD

**Issue by lmikelsons** [SciML/DifferentialEquations.jl#851]
It seems that most of the implicit ODE solvers (Radau, Rosenbrock, Rodas, ...) calculate a "fresh" jacobian in every time step. Even with autodiff=false.
While I'm not sure (well I guess it's fine since it is implemented that way) how that concepts performs on pure Julia rhs's (meaning a AD computed jacobian is available) compared to traditional updates (e.g. only when a newton iteration fails), it leads to awful performance on problems where the rhs's is not pure Julia and costly (e.g. in case of FMUs). Here, AD doesn't work for a cheap jacobian. We get a >factor 10 better performance using CVODE_BDF for our current model, just because of less jacobian generations. So, is there a possibility to influence the jacobian generation for the ODE solvers apart from CVODE?

**Comment by ChrisRackauckas** [comment]
It depends on the ODE solver. Rosenbrock and Rodas calculate a fresh Jacobian every time step because that's what they do. Those are very fast for small problems but do not scale. This is all in the recommendations. Did you try methods like TRBDF2, QNDF, or FBDF?

**Comment by lmikelsons** [comment]
Yep, tried also QNDF, FBD, TRBDF2, Radau. All of them have number of jacobian generation greater or equal accepted steps.
At least for Radau I'm quite sure that the original implementation does not compute a fresh jacobian in every time step.  
Our model is not really large scale, but mid-size (N= 320). CVode (and also SDIRK solvers in other environments) require 2-5 jacobian updates (compared e.g. to >100 using QNDF2)

**Comment by ChrisRackauckas** [comment]
All of those methods do not compute a fresh Jacobian in every time step. Are you using the non-caching out of place interface or something?

**Comment by lmikelsons** [comment]
We used the out of place interface for the rhs (we know that in place leads to better performance in general).
But: Wouldn't have guessed that this could influence the jacobian update rate....but it does!
Thanks a lot for your help!
