### ISSUE TITLE
Long time precompilation 

### ISSUE THREAD

**Issue by CaiYitao** [SciML/DifferentialEquations.jl#858]
When I install DifferentialEquations.jl it took very long time
<img width="790" alt="image" src="https://user-images.githubusercontent.com/65641330/162983997-45db4c88-2326-4557-aa69-8560880709dd.png">

What could be the problem?

and it is still in process when using it. before adding DifferentialEquations, it would took around 70s(which is also very long time compare to Python), after using DifferentialEquations, showed as following
<img width="743" alt="image" src="https://user-images.githubusercontent.com/65641330/162984614-83a63f4e-9af7-4ff4-a1b3-10b602f1733c.png">
edited: after closing the notebook and rerun it, then it is in an acceptable range.

**Comment by ChrisRackauckas** [comment]
Julia v1.7? I get:

```
  59 dependencies successfully precompiled in 117 seconds (69 already precompiled)
```

But anyways, this speed is a Base Julia thing, and not much to do in this repo. It is consistently getting better and Julia Base does track this.

**Comment by CaiYitao** [comment]
my julia is v1.8, mac os Catalina, maybe because mine need to compile more things? 569sec/261 = 2.18 sec per compile time -> 117sec /69 = 1.69 sec per compile time
