### ISSUE TITLE
An SDEProblem with non-default noise_rate_prototype has issues dealing with complex-valued problems

### ISSUE THREAD

**Issue by yanagimotor** [SciML/DifferentialEquations.jl#865]
I stumbled upon an issue with an SDEProblem defined with a non-default `noise_rate_prototype` argument when the problem is "complex-valued". An almost-minimum code that produces an error on my environment (StochasticDiffEq v6.47.0) is shown below:
```
function f(du,u,p,t)
    du .= 0.0im
end

function g(du,u,p,t)
    du[1,1] = 1.0im
    du[1,2] = 1.0im
    du[2,1] = 1.0im
    du[2,2] = 1.0im
end

u0 = [0.0im,0.0im]
dt = 0.001
prob = SDEProblem(f,g,u0,(0.0,1.0),noise_rate_prototype=zeros(2,2))
sol = solve(prob,EM(),dt=dt)
```

An error that I get is an "InexactError: Float64(0.0 + 1.0im)", which is caused by trying to substitute `1.0im` to `du[1,1]`. Here, what seems to be happening is that the type of `du` for the function `g(du,u,p,t)` is set to `Matrix{Float64}`, despite that it should have been inferred as `Matrix{ComplexF64}` from the type of an initial state `u0`. In other words, it appears that the program fails to infer the type of `u` from the given initial value (i.e., `u0`) when `u0` takes a complex type. In fact, replacing all the complex substitutions in `g` as
```
function g(du,u,p,t)
    du[1,1] = 1.0
    du[1,2] = 1.0
    du[2,1] = 1.0
    du[2,2] = 1.0
end
```
suppresses the error. 

This issue seems to appear only when one tries to use an SDEProblem with non-default `noise_rate_prototype`, e.g., when solving an SDE problem with non-diagonal noise. Could you please help resolving/fixing the issue?

**Comment by ChrisRackauckas** [comment]
> An error that I get is an "InexactError: Float64(0.0 + 1.0im)", which is caused by trying to substitute 1.0im to du[1,1]. Here, what seems to be happening is that the type of du for the function g(du,u,p,t) is set to Matrix{Float64}, despite that it should have been inferred as Matrix{ComplexF64} from the type of an initial state u0.

No, you chose the type here. `zeros(2,2)` is a `Matrix{Float64}`, and so with `noise_rate_prototype=zeros(2,2)` you're directly telling it that the rate `du` matrix in `g` should be real-valued. Then you got an error that it couldn't have complex values. If you want it to support complex values, you'd do `noise_rate_prototype=zeros(ComplexF64,2,2)`

We could think of doing a scheme for type promotion, i.e. promote the element type of noise_rate_prototype based on u0 and possibly p, but that's not done right now.  But that's completely separate from any type inference

**Comment by yanagimotor** [comment]
@ChrisRackauckas Thanks a lot you for the reply!

Now I understand that the `noise_rate_prototype` is a place where we specify the structure of the random noise, including its type (e.g., real or complex). Also it makes sense that the issue here is independent from the type inference. Modifying the code as you suggested (shown below) has successfully resolved the present error.
```
function f(du,u,p,t)
    du .= 0.0im
end

function g(du,u,p,t)
    du[1,1] = 1.0im
    du[1,2] = 1.0im
    du[2,1] = 1.0im
    du[2,2] = 1.0im
end

u0 = [0.0im,0.0im]
dt = 0.001
prob = SDEProblem(f,g,u0,(0.0,1.0),noise_rate_prototype=zeros(ComplexF64,2,2));
sol = solve(prob,EM(),dt=dt);
```

With the code above, I was naïvely expecting to implement an SDE of the form
du1 = im (dW1 + dW2)
du2 = im (dW1 + dW2)
where dW's are _real_-valued Wiener increments (here, `du` still becomes complex) in which case, `u` should remain purely imaginary. 

On the other hand, looking at the `sol` produced by the code, it seems that the Wiener increments (i.e., dW's) themselves have become complex-valued by using `noise_rate_prototype=zeros(ComplexF64,2,2)` (I see `sol` contains non-zero real component). I guess this is an intended behavior, but I still wonder if there is a way to implement an SDE with complex-valued `du` with real-valued Wiener increments (e.g., the SDE shown above)? I feel it would be convenient if one does not need to "separate" the real and imaginary parts of `u` to transform the problem into an all-real-valued form when handing a problem of this type.

**Comment by yanagimotor** [comment]
Regarding the latter point, I think now I see a solution (Thanks @danielwe for the help!); By specifically setting the noise process as real Wiener processes, we can implement an SDE with complex `du` driven by real dW's.
```
u0 = [0.0im,0.0im]
dt = 0.001

W = WienerProcess!(0.0,zeros(2),zeros(2))
prob = SDEProblem(f,g,u0,(0.0,1.0),noise_rate_prototype=zeros(ComplexF64,2,2),noise=W)
sol = solve(prob,EM(),dt=dt)
```
I believe it now all makes sense!

**Comment by ChrisRackauckas** [comment]
Awesome, good to see.
