### ISSUE TITLE
Change return codes to Enum

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DifferentialEquations.jl#867]
This is safer than using Symbols as was originally done, but it's also breaking to make this change.

When should we do it? I've been waiting to make this one for awhile, but there will be a lot of packages to push around if we do the breaking in SciMLBase and DiffEqBase so I haven't wanted to do it.

**Comment by thomvet** [comment]
Can you comment on how/where/which context it’s safer? 

(when deciding whether a breaking change “is worth it”, would be good to know the perceived value of the change?)

**Comment by ChrisRackauckas** [comment]
Retcodes are currently symbols. `if sol.retcode == :Sucess` is a valid statement. But wait, that had a typo, it should be `if sol.retcode == :Success`. Too bad the first statement is valid, even though it's impossible for `retcode` to ever be `:Sucess`. However, if it was an enum``sol.retcode == SciMLBase.Sucess`, it would give an error that `Sucess` is not defined.

**Comment by fjebaker** [comment]
How would you recommend doing custom return codes with this, or is that not possible any more? I had been using symbol retcodes as a flag for tracking the circumstances under which a solve terminates (for filtering later during analysis) but that doesn't work with the enum changes.

**Comment by ChrisRackauckas** [comment]
It does set enums for tracking the circumstances under which a solve terminates though? I'm confused at that. Open a new issue and we can discuss it. If one needs a separate retcode for problem specific information, I would probably just put that in the parameters?

**Comment by fjebaker** [comment]
The latter was what I was addressing, i.e.
```julia
terminate!(i, :Custom)
```
but your suggestion of putting it into parameters is a perfectly acceptable solution, that, for whatever reason, escaped me. Thanks!
