### ISSUE TITLE
How to customize solver algorithm: May be needed in some physical problem.

### ISSUE THREAD

**Issue by fangrh** [SciML/DifferentialEquations.jl#873]
In the document, the code below can get a serial of solutions with time step of 1e-8.
`sol = solve(prob, Tsit5(), saveat=1e-8)`
However, in some case, we only concern about the sum of these solutions. To achieve this, I get a serial of solutions firstly and then calculate the sum of these solutions. This cost may memory resource since we should save all the solutions in memory.
My question is

1. Can we just calculate the sum of solutions at every step.
2. Is there possible to customize solver algorithm as like Tsit5(), TRBDF2() ...

**Comment by ChrisRackauckas** [comment]
> Is there possible to customize solver algorithm as like Tsit5(), TRBDF2() ...

What do you mean?

> Can we just calculate the sum of solutions at every step.

Yes, see the documentation on SavingCallback. https://diffeq.sciml.ai/stable/features/callback_library/#saving_callback

**Comment by fangrh** [comment]
> Yes, see the documentation on SavingCallback. https://diffeq.sciml.ai/stable/features/callback_library/#saving_callback
Thanks very much.

> What do you mean?
`sol = solve(prob, alg, saveat=1e-8)`
I mean how to customize algorithm for the `alg` argument.

**Comment by fangrh** [comment]
>Yes, see the documentation on SavingCallback. https://diffeq.sciml.ai/stable/features/callback_library/#saving_callback

Thanks very much.

>What do you mean?

`sol = solve(prob, alg, saveat=1e-8)`
I mean how to customize algorithm for the `alg` argument.

**Comment by ChrisRackauckas** [comment]
Customize what?

**Comment by fangrh** [comment]
Customize `OrdinaryDiffEqAdaptiveAlgorithm` or `OrdinaryDiffEqAdaptiveAlgorithm`

**Comment by fangrh** [comment]
Customize `OrdinaryDiffEqAlgorithm` or `OrdinaryDiffEqAdaptiveAlgorithm`

**Comment by ChrisRackauckas** [comment]
I still have no idea what you're asking for. Customizing what about them? Do you mean https://diffeq.sciml.ai/stable/solvers/ode_solve/#Extra-Options ?

**Comment by fangrh** [comment]
> I still have no idea what you're asking for. Customizing what about them? Do you mean https://diffeq.sciml.ai/stable/solvers/ode_solve/#Extra-Options ?

Although it is different from my origin diea, maybe this is a more fashionable way. Let me try. Thanks again.

**Comment by ChrisRackauckas** [comment]
Can you describe what you're asking for?

**Comment by fangrh** [comment]
I want to customized the `MyCustomAlgorithm`

`using DifferentialEquations`
`f(u,p,t) = 1.01*u`
`u0 = 1/2`
`tspan = (0.0,1.0)`
`prob = ODEProblem(f,u0,tspan)`
`struct MyCustomAlgorithm <: OrdinaryDiffEqAdaptiveAlgorithm end  # I want to customize a algorithm.`
`sol = solve(prob, MyCustomAlgorithm(), reltol=1e-8, abstol=1e-8)  # And used for solve function`

**Comment by ChrisRackauckas** [comment]
See the developer docs section.

https://docs.sciml.ai/dev/modules/DiffEqDevDocs/contributing/adding_packages/

https://github.com/SciML/SimpleDiffEq.jl/blob/master/src/tsit5/gpuatsit5.jl are some simple examples.
