### ISSUE TITLE
DiscreteProblem keyword scale_by_time=true

### ISSUE THREAD

**Issue by raphaelchinchilla** [SciML/DifferentialEquations.jl#875]
According to the [documentation of DiscreteProblem](https://docs.juliahub.com/DifferentialEquations/UQdwS/6.15.0/types/discrete_types/) it says
`Note that if the discrete solver is set to have scale_by_time=true`

I cannot find where to set such option. I have tried as a keyword both at the problem construction and at the problem solution and I get a warning saying that the keyword argument is not found.

**Comment by ChrisRackauckas** [comment]
https://diffeq.sciml.ai/stable/solvers/discrete_solve/#OrdinaryDiffEq.jl

`FunctionMap(scale_by_time=true)` we probably need to highlight that better.
