### ISSUE TITLE
how to obtain the noise realization?

### ISSUE THREAD

**Issue by yuyuexi** [SciML/DifferentialEquations.jl#882]
Hi, I am using `DifferentialEquations.jl` to solve some SDEs in my project, and i want to know how to obtain the noise realizations of the solution ensembles?

Let me describe the question more precisely using example $dx=xdt+axdw$.

We can numerically solve this SDE by randomly choosing $\Delta w$ in a small time interval (correct me if not in this case).
Now, i want to obtain $dm=f(x,t)dt+kdw$. 

Naively, i have to obtain the noise realization $\Delta w$ at different time.

So, in `DifferentialEquations.jl`, how can we obtain the noise realization $\Delta w$?

Many thanks!

**Comment by ChrisRackauckas** [comment]
use `save_noise` in the solve and then `sol.W` is the solution. This is covered in the documentation here: https://diffeq.sciml.ai/dev/types/rode_types/#SciMLBase.RODESolution . Let me know if you need anything else.

**Comment by ChrisRackauckas** [comment]
The noise function is continuous `W(t)` so evaluate it where you want. If time stepping was adaptive then it will use the Brownian bridge to back fill values according to the right distribution.
