### ISSUE TITLE
Some contradictory fields in SteadyStateProblem

### ISSUE THREAD

**Issue by Funkerfish** [SciML/DifferentialEquations.jl#894]
DifferentialEquations v7.2.0

Hi! I just updated the package and my code cannot work now.

The error message is: ```type SteadyStateProblem has no field tspan```.
I defined a ```SteadyStateProblem``` via ```SteadyStateProblem(prob::ODEProblem)```, which requires a tspan when defining a ```ODEProblem```. I try to calculate the steady state and then the error message comes. Could you help me?

here is my code:
```
function test!(du, u, p, t)
    k1, k2 = p
    x, y = u
    du[1] = k1 * (y - x)
    du[2] = k2 * x - y - x 
end
u0 = [0.1, 0.01]
para = [1.0, 0.0]
tspan_findsteady = (0.0, 100.0)
prob_findsteady = ODEProblem(test!, u0, tspan_findsteady, para)
prob_s = SteadyStateProblem(prob_findsteady)
find_steady_sol = solve(prob_s, DynamicSS(AutoTsit5(Rosenbrock23())))
```

**Comment by Funkerfish** [comment]
I understand that I can fix this by directly defining the ```SteadyStateProblem```. I just want to know that would ```SteadyStateProblem``` continue to support the direct definition from ODEProblem?

**Comment by ChrisRackauckas** [comment]
Thanks for the report. I'm flying around today but hopefully will get to this soon enough. It's not a hard fix, it's in the DiffEqBase higher level handling.

**Comment by ChrisRackauckas** [comment]
This is fixed, and better downstream tests now guard against this.

**Comment by Funkerfish** [comment]
thank you! Your SciML packages are really remarkable！Hope someday I can contribute to this ecosystem!
