### ISSUE TITLE
[help] Difficulty adapting Matlab code to Julia

### ISSUE THREAD

**Issue by lucasmsoares96** [SciML/DifferentialEquations.jl#897]
Hello guys. I'm having trouble adapting a Matlab code that resolves a second-order ODE to the Julia equivalent.

This is the code in Matlab. It plots a graph with 3 curves:

```matlab
syns y(x);
dy = diff(y);
edo = diff(y,x,2) == -0.1 * dy - 0.8 *y;

Bound_1 = y(1) == 5e-3;
Bound_2 = dy(1) == 0;
conds = [Bound_1 Bound_2]
t = [0, 30]

ySol(x) = dsolve(edo,conds);

figure(1)
fplot(ySol,t)
hold on
fplot(diff(ySol),t)
fplot(diff(ySol,2),t)
hold off
```

This is my equivalent Julia version. However, the resulting graph has only two curves.

```julia
f2(du, u, p, t) = -0.1du - 0.8u
u₀ = 5e-3
du₀ = 0.0
t = (0.0, 30.0)
prob = SecondOrderODEProblem(f2, du₀, u₀, t)
sol = solve(prob)
plot(sol)
```

Any tips on how to resolve this?

**Comment by TS-CUBED** [comment]
This type of question would be better asked on the Julia Discourse forum. https://discourse.julialang.org/

**Comment by ChrisRackauckas** [comment]
You define a second order ODE with one state variable, so it has two states: `u` and `u'`. There is no third curve to be had. Are you also looking to plot `u''`?

**Comment by lucasmsoares96** [comment]
> You define a second order ODE with one state variable, so it has two states: `u` and `u'`. There is no third curve to be had. Are you also looking to plot `u''`?

Yes.

**Comment by ChrisRackauckas** [comment]
You can get those values from `sol(t,Val{1})` as mentioned in the docs. Hopefully that helps. As mentioned, for usage questions please use the Discourse. Closing as there no actionable package development issue here, but feel free to ask more questions on the Discourse.
