### ISSUE TITLE
Lagrangian Descriptors

### ISSUE THREAD

**Issue by rmsrosa** [SciML/DifferentialEquations.jl#899]
I suggested implementing this idea of **Lagrangian descriptors** described in [Painting the Phase Portrait of a Dynamical System with the Computational Tool of Lagrangian Descriptors, by S. Wiggins & V. J. García-Garrido (AMS Notices June/July 2022](https://www.ams.org/journals/notices/202206/noti2489/noti2489.html?adat=June/July%202022&trk=2489&galt=none&cat=feature&pdfissue=202206&pdffile=rnoti-p936.pdf)) and @Datseris suggested I open an issue somewhere so we could track this.

We could implement it at [JuliaDynamics/DynamicalSystems.jl](https://github.com/JuliaDynamics/DynamicalSystems.jl) or somewhere here at [SciML](https://github.com/SciML).

**Comment by ChrisRackauckas** [comment]
I think this either makes sense in DynamicalSystems.jl or in its own package (which could live in SciML). I am a bit at a loss as to what other package it could fit into.

**Comment by rmsrosa** [comment]
Yeah, it actually makes it easier for development to start in its own package, and then we think about whether to include it in DynamicalSystems.jl or not

**Comment by rmsrosa** [comment]
I just to mention another and simpler way of doing it. Instead of augmenting, just solve the original system and integrate the descriptor over the solution.

**Comment by Datseris** [comment]
Yeah this fits well in DynamicalSystems.jl, but I'd still make it its own module/package initially that you can host in JuliaDynamics if you want. I've invited you to the org already! Simpler ways to do things are definitely preferred in my mind!

**Comment by rmsrosa** [comment]
Thanks @ChrisRackauckas and @Datseris! Let's make it a `JuliaDynamics/LagrangianDescriptors.jl`, then!

PS: The simpler versions is tempting, but this is a demanding computation since we'll repeat solving the systems so many times. We will play with both versions and see if the more involved one has a clear performance advantage or not.

**Comment by rmsrosa** [comment]
I started the project at [JuliaDynamics/LagrangianDescriptors.jl](https://github.com/JuliaDynamics/LagrangianDescriptors.jl) (it has a README at least! 😆 ), so I guess I will just close this issue.
