### ISSUE TITLE
 MethodError: no method matching setindex(::Vector{Float64}, ::Float64, ::Int64)

### ISSUE THREAD

**Issue by pjssilva** [SciML/DifferentialEquations.jl#911]
The following code is a small variation of the code that appear in the help of `ODEProblem` (One parameter of the ODE is different, the lorenz function is not inplace, and it does not specify the `Tsit5()` solver):

```julia
using DifferentialEquations
function lorenz(u, p, t)
    d1 = 10.0(u[2] - u[1])
    d2 = u[1] * (10.0 - u[3]) - u[2]
    d3 = u[1] * u[2] - (8 / 3) * u[3]
    return [d1, d2, d3]
end
u0 = [1.0; 0.0; 0.0]
tspan = (0.0, 100.0)
prob = ODEProblem(lorenz, u0, tspan)

# Test that it worked
sol = solve(prob)
``` 
It crashes with `MethodError: no method matching setindex(::Vector{Float64}, ::Float64, ::Int64)`. The error actually happens in the line 196 of the file jacobian.jl of the FiniteDiff.jl package. It seems that it is expecting a tuple (for which `setindex` is defined) but gets a Vector (for which only `setindex!` is defined). If I change `setindex` to `setindex!` in that point, the error disapears. But I am not sure whether the problem is in DifferentialEquations.jl that is sending a Vector in place of a Tuple of in FiniteDiff.jl.

**Comment by ChrisRackauckas** [comment]
Thanks, there was a hiccup in the system but on latest packages this is fixed.
