### ISSUE TITLE
NeuralSDE Example 

### ISSUE THREAD

**Issue by ChrisVL1** [SciML/DifferentialEquations.jl#914]
Hi @ChrisRackauckas 

Why do you use NeuralDSDE as opposed to NeuralSDE? What would be the difference if you used NeuralSDE?

I am referring to this example: https://docs.sciml.ai/DiffEqFlux/stable/examples/neural_sde/

**Comment by ChrisRackauckas** [comment]
That's using a diagonal noise neural SDE layer (D = diagonal). General NeuralSDE is slower to train and cannot use methods which specialize on the noise form.

**Comment by ChrisRackauckas** [comment]
Yes, but it's a specialization. Is `g` returning a matrix or a vector?

**Comment by ChrisVL1** [comment]
> That's using a diagonal noise neural SDE layer (D = diagonal). General NeuralSDE is slower to train and cannot use methods which specialize on the noise form.

I could be interpreting the graphs incorrectly, but are you training two different neuralSDEs, hence the two sets of data and predictions?

**Comment by ChrisVL1** [comment]
> 

I want to train a neural SDE where drift(S,p,t) = r*S; # The drift function in the SDE, and diffusion(S,p,t) = some neural network ; # The noise function in the SDE.

**Comment by ChrisRackauckas** [comment]
> I could be interpreting the graphs incorrectly, but are you training two different neuralSDEs, hence the two sets of data and predictions?

No just one.

I think the confusion you have here is the difference between diagonal noise and non-diagonal noise SDEs. You may want to check out this part of the SDE tutorial:

https://docs.sciml.ai/DiffEqDocs/stable/tutorials/sde_example/#Example-2:-Systems-of-SDEs-with-Diagonal-Noise

**Comment by ChrisRackauckas** [comment]
We do need some more tutorials. There's the docstring https://docs.sciml.ai/DiffEqFlux/stable/layers/NeuralDELayers/#DiffEqFlux.NeuralSDE which describes what to do. It's the same as the NeuralDSDE, but `g` needs to return the matrix instead of the vector.

**Comment by ChrisVL1** [comment]
Is there a difference between using neuralSDE and just using SDEProblem and inputting neural networks for f and g as done in the beginning of this tutorial https://docs.sciml.ai/DiffEqFlux/stable/examples/neural_sde/ ?

**Comment by ChrisVL1** [comment]
Thanks for all the help. Last question 😅 ,  I am attempting to train a neural SDE with Geometric Brownian motion data, where only the diffusion is a NN. I am getting this error, not sure why, as I have followed the tutorial in most cases. 

<img width="1122" alt="Screenshot 2022-11-22 at 17 03 04" src="https://user-images.githubusercontent.com/118824751/203348081-4bbe9584-219c-4615-9569-a5e40d0f8db6.png">

Sorry I'm not too sure how to share my notebook.

**Comment by ChrisRackauckas** [comment]
In `NeuralSDE`, both the drift and diffusion have to be Flux-style chain objects with the call structure `chain(u,parmas)`, so your drift function doesn't make sense there. Try doing the direct definition of an SDE form.

Somehow it passes some early checks and then throws a weird error though: we should fix that part.
