### ISSUE TITLE
SDE solver fixed 

### ISSUE THREAD

**Issue by ChrisVL1** [SciML/DifferentialEquations.jl#915]
Hi @ChrisRackauckas 

Is it possible to solve an SDE using  "solve" with the same generated random variables (i.e. the same Brownian motions)? I want to compare two different SDEs but need to use the same random variables so that they are comparable.

**Comment by ChrisRackauckas** [comment]
See https://docs.sciml.ai/DiffEqNoiseProcess/stable/ 

Specifically https://docs.sciml.ai/DiffEqNoiseProcess/stable/abstract_noise_processes/#DiffEqNoiseProcess.NoiseWrapper or just using a NoiseGrid.
