### ISSUE TITLE
Implicit Euler and  @btime report Warning: Instability detected. Aborting

### ISSUE THREAD

**Issue by malinjlu** [SciML/DifferentialEquations.jl#921]
using DifferentialEquations
using Plots
using BenchmarkTools

function f1(du,u,p,t)
 du[1] = u[2]
 du[2] = -u[1]-0.15*u[2]
 du[3] = u[2]+2*u[3]
 du[4] = -u[3]+0.8*u[4]
 du[5] = 0.3*u[4]+u[5]
 du[6] = u[5]+0.8*u[6]
 du[7] = -u[6]+u[7]
 du[8] = u[7]-u[8]
 du[9] = 3*u[8]-u[9]
 du[10] = u[9]-u[10]
end

function j!(J, x)
    for i=1:10
          for j=1:10
                J[i,j]=0
          end
    end
    J[1,2] = 1
    J[2,1] = -1
    J[2,2] =-0.15
    J[3,2] = 1
    J[3,3] = 2
    J[4,3] =-1
    J[4,4] =0.8
    J[5,4] =0.3
    J[5,5] =1
    J[6,5]=1
    J[6,6]=0.8
    J[7,6]=-1
    J[7,7]=1
    J[8,7]=1
    J[8,8]=-1
    J[9,8]=3
    J[9,9]=-1
    J[10,9]=1
    J[10,10]=-1
end

u0 = [1.0;0.0;0.0;1.0;0.5;-0.3;1.0;0.5;-0.3;-0.1]
tspan = (0.0,10000.0)

f=ODEFunction(f1;jac_prototype=j!)
prob=ODEProblem(f,u0,tspan)

sol= solve(prob,ImplicitEuler(autodiff=false,diff_type=Val{:central}))

print("end solve!!!!")

----------------------------------------------------------------------------
I use Implicit Euler to solve the ODEs, but it shows that 

Warning: Instability detected. Aborting
└ @ SciMLBase C:\Users\PC\.julia\packages\SciMLBase\QqtZA\src\integrator_interface.jl:525

Interpolation: 3rd order Hermite  

when I use @btime, not the implicit euler.

**Comment by ChrisRackauckas** [comment]
Yes, the solution blows up to infinity in finite time. It has an analytical solution:

```julia
A = zeros(10,10)
j!(A, nothing)
t = 50
exp(A*t)*u0
```

so it's clearly just a property of the solution (can also just be checked by the unstable eigenvalues).
