### ISSUE TITLE
error compiling: due to `N_VMake_Serial`

### ISSUE THREAD

**Issue by SimonEnsemble** [SciML/DifferentialEquations.jl#928]
I'm using `DifferentialEquations.jl` for my process dynamics class of 80 students! so far, two students using Windows could not get `DifferentialEquations.jl` to compile, due to an identical compile error. please see the screenshots below. I asked them to use `up` to update packages but this did not solve the issue. any idea of what else to try? thanks.

![image](https://user-images.githubusercontent.com/30643894/212457068-ec3f4c35-c5dd-42f3-b1ff-ff4621e95fa3.png)

![image](https://user-images.githubusercontent.com/30643894/212457076-7f7e50ed-4269-460d-b570-656055fe5ef2.png)

![image](https://user-images.githubusercontent.com/30643894/212457062-54c0c6a7-15aa-4a5a-ae28-bee6b50be640.png)

**Comment by ChrisRackauckas** [comment]
Why did they install the 32-bit version? Is this using Windows XP 32-bit or something?

**Comment by SimonEnsemble** [comment]
I see---they must have installed the 32 bit version of Julia from here instead of the 64 bit version?
https://julialang.org/downloads/
thanks. closing for now and will report back if this was not the case...

**Comment by ChrisRackauckas** [comment]
WORD_SIZE = 32 would be 32-bit. Microsoft hasn't released a 32-bit Windows in like a decade: we should just remove those from the downloads page.
