### ISSUE TITLE
Issue with the use of Measurements.jl

### ISSUE THREAD

**Issue by ssemigr** [SciML/DifferentialEquations.jl#959]
The first example from SciML book [16. Uncertainty Programming, Generalized Uncertainty Quantification](https://book.sciml.ai/notes/19-Uncertainty_Programming-Generalized_Uncertainty_Quantification/) of using together DifferentialEquations and Measurements libraries

> using OrdinaryDiffEq, Measurements
gaccel = 9.79 ± 0.02; # Gravitational constants
L = 1.00 ± 0.01; # Length of the pendulum
#Initial Conditions
u₀ = [0 ± 0, π / 3 ± 0.02] # Initial speed and initial angle
tspan = (0.0, 6.3)
#Define the problem
function simplependulum(du,u,p,t)
    θ  = u[1]
    dθ = u[2]
    du[1] = dθ
    du[2] = -(gaccel/L) * sin(θ)
end
#Pass to solvers
prob = ODEProblem(simplependulum, u₀, tspan)
sol = solve(prob, Tsit5(), reltol = 1e-6)

doesn't work anymore, the error is `MethodError: no method matching Float64(::Measurement{Float64})`.

**Comment by ChrisRackauckas** [comment]
This was fixed, tested, and on latest versions runs fine. Please update to the latest versions.

For a full sense of what was fixed, see https://github.com/SciML/DifferentialEquations.jl/issues/950
