### ISSUE TITLE
Method Error in solver FBDF with LinearSolve v2.2.1

### ISSUE THREAD

**Issue by ytdHuang** [SciML/DifferentialEquations.jl#967]
Hi,

I'm solving a SteadyStateProblem with solver `FBDF(autodiff=false)`.
It has no problem when the version of the package `LinearSolve` is `v1.42.0`
However, it appears an error when I update `LinearSolve` to `v2.2.1`

Here is the pseudo-code:
```julia
# OrdinaryDiffEq@v6.53.2
import OrdinaryDiffEq: DiffEqArrayOperator, ODEProblem, SteadyStateProblem, solve, FBDF

# SteadyStateDiffEq@v1.15.0
import SteadyStateDiffEq: DynamicSS
```
The ODE problem can be expressed as:
```math
\frac{d u(t)}{dt} = M u(t),
```
where $M$ is independent with $t$.

```julia
M  # some large sparse matrix in the type: SparseMatrixCSC{ComplexF64, Int64}
u0 # initial condition

L = DiffEqArrayOperator(M)
prob = ODEProblem(L, u0, (0, Inf))

# solving steady state of the ODE problem
sol = solve(
    SteadyStateProblem(prob), 
    DynamicSS(FBDF(autodiff=false); abstol = 1e-8, reltol = 1e-6);
    maxiters = 1e5,
    save_everystep = false
)
```
And the main error message are as follows:
```
ERROR: LoadError: MethodError: no method matching size(::Nothing)
```
I think there is something wrong when the solver `FBDF` calls the function in `LinearSolve`  package, which is not compatible with `v2.2.1` 

I have tried some solvers, and `FBDF` is the most efficient and suitable one for my case so far. 
But I also need to use `LinearSolver v2.2` for other purposes.

Does anyone have any idea?

**Comment by ChrisRackauckas** [comment]
Try just changing it to `L = MatrixOperator(A)` with `using SciMLOperators`. DiffEqOperators has been in the deprecation path for awhile. While I'm surprised it would now break, it should still be working (and throw a warning to upgrade), but you should also update this.

**Comment by ytdHuang** [comment]
@ChrisRackauckas 
Thank you for the suggestion.
After I use `MatrixOperator` instead of `DiffEqOperator`, there is no error anymore.

However, I obtain a new warning, and I found out that the solving process aborted immediately.
```
┌ Warning: dt(2.220446049250313e-16) <= dtmin(2.220446049250313e-16) at t=0.0, and step error estimate = 1.0. Aborting. There is either an error in your model specification or the true solution is unstable.
└ @ SciMLBase ~/.julia/packages/SciMLBase/s9wrq/src/integrator_interface.jl:599
```
But this case is solvable in the previous implementation of `FBDF` with `Linearsolve@v1.42`.
I have adjust some extra solver option, such as `dt`, `abstol` and `reltol`, 
```julia
sol = solve(
    SteadyStateProblem(ODEProblem(MatrixOperator(M), u0, (0, Inf))), 
    DynamicSS(FBDF(); abstol = 1e-8, reltol = 1e-6);
    maxiters = 1e5,
    save_everystep = false,
    dt = 1e-3
)
```
but this warning message still pops out.
Also, it seems that the option `dt` is not adjustable for this solver? Because the warning message still says `dt(2.220446049250313e-16)`

Any extra solver options  which are adjustable or other ideas to make it behave as the previous ver. ?

**Comment by ytdHuang** [comment]
I tried the following solvers : `FBDF`, `QNDF`, `Rodas4`, `Rodas5`.
They all have the same issue.
My case is a stiff-problem. Since there will be a warning if I use non-stiff solvers (e.g., `DP5`)

**Comment by ChrisRackauckas** [comment]
@vpuri3 can you look at this case?

**Comment by vpuri3** [comment]
I am getting the same error with `Tsit5()` and a not stiff `M = Diagonal([1, 1/2, 1/3, 1/4])`. This means it's not related to LinearSolve. Will look at it later in the day.

**Comment by ChrisRackauckas** [comment]
Wait, mass matrix with Tsit5? You can't do mass matrix with an explicit RK method. It should be throwing an error in that case.

**Comment by vpuri3** [comment]
```julia
using OrdinaryDiffEq, SteadyStateDiffEq, LinearAlgebra

N = 4
M = Diagonal(1 ./ (1:N)) |> Array
u0 = ones(N)

# L = MatrixOperator(M)
L = (u, p, t) -> M * u
odeprob = ODEProblem(L, u0, (0, Inf))

odealg = Tsit5()

prob = SteadyStateProblem(odeprob)
alg = DynamicSS(odealg)

sol = solve(prob, alg; maxiters = 1e5, save_everystep = false)
```

```julia
julia> include("a.jl") 
┌ Warning: Instability detected. Aborting                                                              
└ @ SciMLBase ~/.julia/packages/SciMLBase/kTUaf/src/integrator_interface.jl:606                        
u: 4-element Vector{Float64}:                                                                          
 2.5139480184424995e50  
 1.6178325409065478e25                                                                                 
 6.3985826749673736e16                                                                                 
 4.0231886093096943e12  
```

**Comment by ChrisRackauckas** [comment]
Okay, well if the ODE is like that then it just doesn't have a steady state of course, so of course it's going to diverge. Without more information I think it just had a MatrixOperator issue which has now been fixed.
