### ISSUE TITLE
taking too long time first using the package

### ISSUE THREAD

**Issue by Zou-Bo** [SciML/DifferentialEquations.jl#988]
Each time it needs 250 seconds to load the package. The version is v7.11.0

(@v1.9) pkg> precompile DifferentialEquations
Precompiling DifferentialEquations
  19 dependencies successfully precompiled in 1250 seconds. 163 already precompiled.

julia> @time using DifferentialEquations
250.903284 seconds (729.28 M allocations: 149.692 GiB, 7.97% gc time, 0.09% compilation time: 48% of which was recompilation)

julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700H
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, alderlake)
  Threads: 10 on 20 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

**Comment by Zou-Bo** [comment]
Somehow it is fixed. I just removed it and added it back. Don't know why.

**Comment by devmotion** [comment]
Probably fixed by the new release of NonlinearSolve (https://github.com/SciML/NonlinearSolve.jl/pull/224).
