### ISSUE TITLE
My ODE peoblems is always Aborting Help!!!

### ISSUE THREAD

**Issue by HaoJieZhang0917** [SciML/DifferentialEquations.jl#992]
I'm trying to calculate a second-order ordinary BVP differential equation problem, but no matter which method I use, my results always show divergence. But I don't know what the problem with my model or boundary conditions is. Is there a professional who can help me? 

The equation is :
**ddu=u^2-v^2+du*w**
**ddv=2*u*v+dv*w**
**dw=-2*u**
![image](https://github.com/SciML/DifferentialEquations.jl/assets/103304790/79710342-c515-4601-bcba-4f2c5c912da1)

My code is :
` using DifferentialEquations

    function Onedisk_BasicFlow_Eqution(du,u,p,t)
        #u[1,2,3,4,5]=[u,v,w,u',v']
        du[1]=u[4]
        du[2]=u[5]
        du[3]=-2.0*u[1]
        du[4]=u[1]*u[1]-u[2]^2 +u[4]*u[3]
        du[5]=2.0*u[1]*u[2] +u[5]*u[3]
    end
    function Onedisk_BasicFlow_bc(residual,u,p,t)
        residual[1]=u[1][1]
        residual[2]=u[1][2]-1
        residual[3]=u[1][3]
        residual[4]=u[end][1]
        residual[5]=u[end][2]
    end
    u0=[0,0,0,0,0]
    tspan=[0.0,5.0]
    Onedisk_BasicFlow = BVProblem(Onedisk_BasicFlow_Eqution,Onedisk_BasicFlow_bc,[0,1,1.2,0,0], tspan)
    prob=Onedisk_BasicFlow
    sol=solve(prob,Rosenbrock23(),abstol = 1e-10, reltol = 1e-10)`

**Comment by ChrisRackauckas** [comment]
That's a boundary value problem. You gave it an ODE solver, not a BVP solver. That doesn't make sense. See the tutorial on BVPs: https://docs.sciml.ai/DiffEqDocs/stable/tutorials/bvp_example/. You need to use a solver for BVPs, like `Shooting(Rosenbrock23())`.

**Comment by zhj2mqforever** [comment]
> That's a boundary value problem. You gave it an ODE solver, not a BVP solver. That doesn't make sense. See the tutorial on BVPs: https://docs.sciml.ai/DiffEqDocs/stable/tutorials/bvp_example/. You need to use a solver for BVPs, like `Shooting(Rosenbrock23())`.

Before this, I have used the `Shooting(Vern8())` method to solve the BVP problem, but the results are still aborting, I think there may be a problem with my model settings and boundary condition settings, but I don't know where the problem is.

**Comment by ChrisRackauckas** [comment]
What is the error message or warning? Is the model stiff? You show a stiff ODE solver earlier, but now you're showing a method only for non-stiff equations.

**Comment by ErikQQY** [comment]
I tested this problem on the latest version of BoundaryValueDiffEq.jl:

- Single Shooting: warning dt<=dtmin, Failure retcode
- Multiple Shooting: warning dt<=dtmin, Successful retcode
- MIRK methods: no warning, Successful retcode

Final solution:

![temporal](https://github.com/SciML/DifferentialEquations.jl/assets/52615090/65c5ad91-45e3-45f5-bdb7-e3937ddad28e)

**Comment by zhj2mqforever** [comment]
> What is the error message or warning? Is the model stiff? You show a stiff ODE solver earlier, but now you're showing a method only for non-stiff equations.

sorry, the model is stiff . Just like the next follower shows , it can be solved by MIRK method , but not for shooting

**Comment by HaoJieZhang0917** [comment]
> I tested this problem on the latest version of BoundaryValueDiffEq.jl:
> 
> * Single Shooting: warning dt<=dtmin, Failure retcode
> * Multiple Shooting: warning dt<=dtmin, Successful retcode
> * MIRK methods: no warning, Successful retcode
> 
> Final solution:
> 
> ![temporal](https://user-images.githubusercontent.com/52615090/277590418-65c5ad91-45e3-45f5-bdb7-e3937ddad28e.png)

How long it takes by using MIRK method?

**Comment by ChrisRackauckas** [comment]
> orry, the model is stiff . Just like the next follower shows , it can be solved by MIRK method , but not for shooting

Yes that's expected. Shooting methods are not as stable as collocation methods, and so for sufficiently difficult problems it will be only the MIRK and similar methods that are stable.

**Comment by HaoJieZhang0917** [comment]
> > orry, the model is stiff . Just like the next follower shows , it can be solved by MIRK method , but not for shooting
> 
> Yes that's expected. Shooting methods are not as stable as collocation methods, and so for sufficiently difficult problems it will be only the MIRK and similar methods that are stable.

Thank you for your help!

**Comment by ErikQQY** [comment]
> But when i use julia,it takes a very long time to use MIRK method,so i just use the shooting .I do not know the reason why it is useless for shooting- _ -

Could you show the version of BoundaryValueDiffEq.jl you are using? It is pretty fast here to get the final result using MIRK methods. @HaoJieZhang0917

**Comment by HaoJieZhang0917** [comment]
> > orry, the model is stiff . Just like the next follower shows , it can be solved by MIRK method , but not for shooting
> 
> Yes that's expected. Shooting methods are not as stable as collocation methods, and so for sufficiently difficult problems it will be only the MIRK and similar methods that are stable.

i have another question , can the parameter tspan be set to a non-equidistant mesh?similar to the Chebyshev method.

**Comment by HaoJieZhang0917** [comment]
> > But when i use julia,it takes a very long time to use MIRK method,so i just use the shooting .I do not know the reason why it is useless for shooting- _ -
> 
> Could you show the version of BoundaryValueDiffEq.jl you are using? It is pretty fast here to get the final result using MIRK methods. @HaoJieZhang0917

The verson of BoundaryValueDiffEq.jl is v4.0.1 . I almost need 15 mins to caculate it through i have setted the dt=0.5...

**Comment by ChrisRackauckas** [comment]
That compile time is fixed with Julia v1.1.0.
