### ISSUE TITLE
Templates for Issues

### ISSUE THREAD

**Issue by prbzrg** [SciML/DifferentialEquations.jl#999]
I think, It would be better if there were some templates for opening issues in all SciML repos.
some points are:

- keeping issues only for development of packages and leading people to _discourse.julialang.org_ for questions or getting help.
- clarifying that we need to know versions of packages and sometimes even version of Julia.
- declaring that issues without minimal reproducible example (MRE) doesn't get needed attention.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by ChrisRackauckas** [comment]
If the template file is added to https://github.com/SciML/.github then it will be added to all of our repos. I would definitely take a contribution which add this.
